const chessSections=[
  {title:['Règles et déplacements','Rules and movement'],lesson:['Les pions avancent tout droit. Depuis sa case initiale, un pion peut avancer de deux cases.','Pawns move straight ahead. From its starting square, a pawn may move two squares.'],goal:['Joue le pion blanc de e2 vers e4.','Move the white pawn from e2 to e4.'],move:['e2','e4'],pieces:{e1:'♔',e2:'♙',e8:'♚',d7:'♟'}},
  {title:['Fourchettes et clouages','Forks and pins'],lesson:['Une fourchette attaque deux pièces à la fois. Le cavalier est particulièrement efficace pour cette tactique.','A fork attacks two pieces at once. Knights are especially effective at this tactic.'],goal:['Place le cavalier de e5 en c6 pour attaquer le roi et la tour.','Move the knight from e5 to c6 to attack the king and rook.'],move:['e5','c6'],pieces:{e5:'♘',e7:'♚',b8:'♜',g2:'♔'}},
  {title:['Enfilades et sortie du clouage','Skewers and escaping pins'],lesson:['Une pièce clouée retrouve sa liberté lorsque le roi quitte la ligne d’attaque.','A pinned piece regains its freedom when the king leaves the line of attack.'],goal:['Déplace le roi blanc de e1 vers d1 pour libérer la tour e2.','Move the white king from e1 to d1 to release the rook on e2.'],move:['e1','d1'],pieces:{e1:'♔',e2:'♖',e8:'♜',a8:'♚'}},
  {title:['Déviation et coups intermédiaires','Decoys and intermediate moves'],lesson:['Une déviation attire ou éloigne un défenseur avant l’action principale.','A decoy attracts or removes a defender before the main action.'],goal:['Joue la dame de h5 vers f7 avec échec pour attirer le roi.','Move the queen from h5 to f7 with check to draw the king.'],move:['h5','f7'],pieces:{h5:'♕',c4:'♗',e8:'♚',f7:'♟',e1:'♔'}},
  {title:['Stratégie et finales de pions','Strategy and pawn endings'],lesson:['En finale, le roi devient une pièce active et aide le pion à atteindre la promotion.','In an endgame, the king becomes active and helps the pawn reach promotion.'],goal:['Avance le roi de e5 vers d6 pour contrôler les cases clés.','Move the king from e5 to d6 to control the key squares.'],move:['e5','d6'],pieces:{e5:'♔',d5:'♙',e7:'♚'}},
  {title:['Paire de fous et réseaux de mat','Bishop pair and mating nets'],lesson:['Deux fous contrôlent ensemble les cases claires et sombres et limitent fortement le roi.','Two bishops control light and dark squares together and strongly restrict the king.'],goal:['Place le fou de c4 en f7 pour fermer une case de fuite.','Move the bishop from c4 to f7 to close an escape square.'],move:['c4','f7'],pieces:{c4:'♗',b2:'♗',h1:'♔',g8:'♚'}},
  {title:['Jeu positionnel et calcul','Positional play and calculation'],lesson:['Une tour devient plus forte sur une colonne ouverte, sans pion devant elle.','A rook becomes stronger on an open file with no pawn in front of it.'],goal:['Place la tour de a1 en d1 sur la colonne ouverte.','Move the rook from a1 to d1 onto the open file.'],move:['a1','d1'],pieces:{a1:'♖',g1:'♔',g8:'♚',c6:'♞',f7:'♟'}}
];
let chessSection=0,chessSelected=null,chessPosition={};
const chessEnglish=()=>localStorage.getItem('mbokaLang')==='en';
function chessCompleted(){try{const value=JSON.parse(localStorage.getItem('mbokaChessProgress')||'[]');return Array.isArray(value)?value:[]}catch{return[]}}
function saveChessSection(){const done=new Set(chessCompleted());done.add(chessSection);localStorage.setItem('mbokaChessProgress',JSON.stringify([...done].sort((a,b)=>a-b)))}
function renderChessSections(){const english=chessEnglish(),done=chessCompleted();document.querySelector('#chessSectionList').innerHTML=chessSections.map((section,index)=>`<button class="chess-section-button ${index===chessSection?'active':''} ${done.includes(index)?'done':''}" data-chess-section="${index}"><span>${index+1}</span><span><small>SECTION ${index+1}</small><strong>${section.title[english?1:0]}</strong></span><span>${done.includes(index)?'✓':''}</span></button>`).join('');document.querySelector('#chessProgressText').textContent=english?`${done.length} / 7 sections mastered`:`${done.length} / 7 sections maîtrisées`;document.querySelector('#chessProgressBar').style.width=`${done.length/7*100}%`}
function renderChessBoard(last=[]){let html='';for(let rank=8;rank>=1;rank--)for(let fileIndex=0;fileIndex<8;fileIndex++){const file='abcdefgh'[fileIndex],square=`${file}${rank}`,piece=chessPosition[square]||'',light=(fileIndex+rank)%2===1;html+=`<button class="chess-square ${light?'light':'dark'} ${square===chessSelected?'selected':''} ${last.includes(square)?'last':''}" data-square="${square}" aria-label="${square}${piece?' '+piece:''}"><span class="chess-piece" aria-hidden="true">${piece}</span><span class="chess-coord">${square}</span></button>`}document.querySelector('#chessBoard').innerHTML=html}
function resetChessExercise(){const section=chessSections[chessSection],english=chessEnglish();chessSelected=null;chessPosition={...section.pieces};document.querySelector('#chessSectionNumber').textContent=`SECTION ${chessSection+1}`;document.querySelector('#chessSectionTitle').textContent=section.title[english?1:0];document.querySelector('#chessLesson').textContent=section.lesson[english?1:0];document.querySelector('#chessObjective').textContent=section.goal[english?1:0];document.querySelector('#chessFeedback').textContent='';renderChessSections();renderChessBoard()}
document.querySelector('#chessBoard').addEventListener('click',event=>{const button=event.target.closest('[data-square]');if(!button)return;const square=button.dataset.square,section=chessSections[chessSection];if(!chessSelected){if(!chessPosition[square]){document.querySelector('#chessFeedback').textContent=chessEnglish()?'Select the piece named in the objective.':'Sélectionne la pièce indiquée dans l’objectif.';return}chessSelected=square;renderChessBoard();return}if(square===chessSelected){chessSelected=null;renderChessBoard();return}const from=chessSelected,piece=chessPosition[from];chessSelected=null;if(from===section.move[0]&&square===section.move[1]){delete chessPosition[from];chessPosition[square]=piece;saveChessSection();document.querySelector('#chessFeedback').textContent=chessEnglish()?'Excellent! The tactical idea is correct.':'Excellent ! L’idée tactique est correcte.';renderChessSections();renderChessBoard([from,square])}else{document.querySelector('#chessFeedback').textContent=chessEnglish()?'Try again and follow the stated objective.':'Essaie encore en suivant précisément l’objectif.';renderChessBoard()}});
document.querySelector('#chessSectionList').addEventListener('click',event=>{const button=event.target.closest('[data-chess-section]');if(!button)return;chessSection=Number(button.dataset.chessSection);resetChessExercise()});
document.querySelector('#chessReset').addEventListener('click',resetChessExercise);
document.querySelector('#chessSpeak').addEventListener('click',event=>{const section=chessSections[chessSection],english=chessEnglish();speakPhrase(`${section.title[english?1:0]}. ${section.lesson[english?1:0]} ${section.goal[english?1:0]}`,event.currentTarget)});
function localizeChessHeader(){const english=chessEnglish();document.querySelector('#chessLab .eyebrow').textContent=english?'Chess laboratory':'Laboratoire d’échecs';document.querySelector('#chessLab h2').innerHTML=english?'Observe, calculate,<br>then move.':'Observer, calculer,<br>puis jouer.';document.querySelector('#chessIntro').textContent=english?'Seven progressive sections to learn rules, tactics, strategy and visualization.':'Sept sections progressives pour apprendre les règles, les tactiques, la stratégie et la visualisation.';document.querySelector('#chessReset').textContent=english?'Restart exercise':'Recommencer l’exercice';document.querySelector('#chessNote').textContent=english?'All positions and explanations in this educational pathway are original. Progress remains on this device.':'Toutes les positions et explications de ce parcours éducatif sont originales. La progression reste sur cet appareil.'}
document.querySelectorAll('.speak-control,.province-speak').forEach(control=>{control.textContent='🔊'});
localizeChessHeader();resetChessExercise();
