(()=>{
  const $=selector=>document.querySelector(selector),form=$('#classModeForm');if(!form)return;
  const storageKey='mbokaClassSessions';
  const activities={quiz:['Quiz RDC','DRC quiz'],sprint:['Sprint des provinces','Province Sprint'],provinces:['Carte des provinces','Province map'],math:['Mathématiques','Mathematics'],memory:['Jeu de mémoire','Memory game'],musicLab:['Musique','Music'],chessLab:['Échecs','Chess'],numerique:['Mboka Numérique','Digital Mboka']};
  const levels={explorer:['Explorateur · 7–10 ans','Explorer · ages 7–10'],adventurer:['Aventurier · 11–14 ans','Adventurer · ages 11–14'],master:['Maître · 15+ ans','Master · ages 15+']};
  const copy={fr:{eyebrow:'MODE CLASSE · LOCAL',title:'Préparer une séance Mboka',intro:'Crée un code de séance et une fiche imprimable. Aucune donnée d’élève n’est envoyée en ligne.',session:'Titre de la séance',school:'Code école ou groupe',level:'Niveau',activity:'Activité',duration:'Durée',goal:'Objectif de la séance',create:'Créer la séance',code:'CODE DE SÉANCE',ready:'SÉANCE PRÊTE',open:'Ouvrir l’activité',print:'Imprimer la séance',export:'Exporter le registre CSV',note:'Utilise ce code comme « code école » dans le pré-test et le post-test pour regrouper les résultats anonymes de cette séance.',minutes:'minutes',objective:'Objectif',historyEyebrow:'REGISTRE LOCAL',history:'Mes séances',empty:'Aucune séance enregistrée sur cet appareil.',one:'séance',many:'séances',reopen:'Rouvrir',remove:'Supprimer',confirm:'Supprimer cette séance locale ?'},en:{eyebrow:'CLASS MODE · LOCAL',title:'Prepare a Mboka session',intro:'Create a session code and printable plan. No learner data is sent online.',session:'Session title',school:'School or group code',level:'Level',activity:'Activity',duration:'Duration',goal:'Session objective',create:'Create session',code:'SESSION CODE',ready:'SESSION READY',open:'Open activity',print:'Print session',export:'Export CSV register',note:'Use this code as the “school code” in the pre-test and post-test to group anonymous results for this session.',minutes:'minutes',objective:'Objective',historyEyebrow:'LOCAL REGISTER',history:'My sessions',empty:'No session saved on this device.',one:'session',many:'sessions',reopen:'Reopen',remove:'Delete',confirm:'Delete this local session?'}};
  const safeSessions=()=>{try{const value=JSON.parse(localStorage.getItem(storageKey)||'[]');return Array.isArray(value)?value:[]}catch{return[]}};
  const clean=value=>String(value||'').trim().replace(/[^\p{L}\p{N} -]/gu,'').slice(0,14).toUpperCase();
  const code=school=>`${clean(school)||'MBOKA'}-${crypto.getRandomValues(new Uint16Array(1))[0].toString(36).toUpperCase().padStart(3,'0').slice(-3)}`;
  let current=null;
  function language(){return localStorage.getItem('mbokaLang')==='en'?'en':'fr'}
  function translate(){const lang=language(),c=copy[lang],ids={classModeEyebrow:'eyebrow',classModeTitle:'title',classModeIntro:'intro',classSessionTitleLabel:'session',classSchoolCodeLabel:'school',classLevelLabel:'level',classActivityLabel:'activity',classDurationLabel:'duration',classGoalLabel:'goal',createClassSession:'create',classSessionCodeLabel:'code',classSessionReadyLabel:'ready',openClassActivity:'open',printClassSession:'print',exportClassSessions:'export',classSessionNote:'note',classSessionHistoryEyebrow:'historyEyebrow',classSessionHistoryTitle:'history'};Object.entries(ids).forEach(([id,key])=>{const el=document.getElementById(id);if(el)el.textContent=c[key]});Object.entries(levels).forEach(([value,label])=>{$(`#classLevel option[value="${value}"]`).textContent=label[lang==='en'?1:0]});Object.entries(activities).forEach(([value,label])=>{$(`#classActivity option[value="${value}"]`).textContent=label[lang==='en'?1:0]});if(current)render(current);renderHistory()}
  function render(session){current=session;const lang=language(),c=copy[lang];$('#classSessionCode').textContent=session.code;$('#classSessionName').textContent=session.title;$('#classSessionSummary').textContent=`${levels[session.level][lang==='en'?1:0]} · ${activities[session.activity][lang==='en'?1:0]} · ${session.duration} ${c.minutes}`;$('#classSessionGoal').textContent=`${c.objective} : ${session.goal}`;$('#openClassActivity').href=`#${session.activity}`;$('#classSessionCard').hidden=false;$('#pilotSchool').value=session.code.slice(0,20)}
  const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  function renderHistory(){const sessions=safeSessions(),lang=language(),c=copy[lang],n=lang==='en'?1:0;$('#classSessionCount').textContent=`${sessions.length} ${sessions.length===1?c.one:c.many}`;$('#classSessionList').innerHTML=sessions.length?sessions.map(session=>`<article class="class-session-row"><div><code>${escapeHtml(session.code)}</code><span>${new Date(session.created_at).toLocaleDateString(lang==='en'?'en-GB':'fr-FR')}</span></div><div><strong>${escapeHtml(session.title)}</strong><span>${escapeHtml(activities[session.activity]?.[n]||session.activity)} · ${escapeHtml(levels[session.level]?.[n]||session.level)} · ${Number(session.duration)||0} ${c.minutes}</span></div><div class="class-session-row-actions"><button type="button" data-reopen-session="${escapeHtml(session.code)}">${c.reopen}</button><button type="button" class="remove" data-remove-session="${escapeHtml(session.code)}">${c.remove}</button></div></article>`).join(''):`<p id="classSessionEmpty">${c.empty}</p>`}
  function csvCell(value){return `"${String(value??'').replace(/"/g,'""')}"`}
  form.addEventListener('submit',event=>{event.preventDefault();const session={code:code($('#classSchoolCode').value),title:$('#classSessionTitle').value.trim(),school:clean($('#classSchoolCode').value),level:$('#classLevel').value,activity:$('#classActivity').value,duration:Number($('#classDuration').value),goal:$('#classGoal').value.trim(),created_at:new Date().toISOString()};const sessions=[session,...safeSessions()].slice(0,50);localStorage.setItem(storageKey,JSON.stringify(sessions));render(session);renderHistory()});
  $('#classSessionList').addEventListener('click',event=>{const reopen=event.target.closest('[data-reopen-session]'),remove=event.target.closest('[data-remove-session]'),sessions=safeSessions();if(reopen){const session=sessions.find(item=>item.code===reopen.dataset.reopenSession);if(session){render(session);$('#classSessionCard').scrollIntoView({behavior:'smooth',block:'center'})}}if(remove&&confirm(copy[language()].confirm)){const next=sessions.filter(item=>item.code!==remove.dataset.removeSession);localStorage.setItem(storageKey,JSON.stringify(next));if(current?.code===remove.dataset.removeSession){current=null;$('#classSessionCard').hidden=true}renderHistory()}});
  $('#openClassActivity').addEventListener('click',()=>{const target=document.getElementById(current?.activity||'quiz');if(target?.hidden){target.hidden=false;target.classList.add('module-revealed')}});
  $('#printClassSession').addEventListener('click',()=>{document.body.classList.add('class-session-printing');window.print()});window.addEventListener('afterprint',()=>document.body.classList.remove('class-session-printing'));
  $('#exportClassSessions').addEventListener('click',()=>{const rows=[['session_code','title','school_or_group','level','activity','duration_minutes','objective','created_at'],...safeSessions().map(item=>[item.code,item.title,item.school,item.level,item.activity,item.duration,item.goal,item.created_at])],blob=new Blob(['\uFEFF',rows.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`mboka-class-sessions-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)});
  new MutationObserver(translate).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});translate();
})();
