// Stage-one interface localization. Educational question packs remain authored in French.
const uiCopy={
  '.primary-nav>a:nth-of-type(1)':['Explorer','Explore'],'.primary-nav>a:nth-of-type(2)':['Provinces','Provinces'],'.primary-nav>a:nth-of-type(3)':['Maths','Maths'],'.primary-nav>a:nth-of-type(4)':['Musique','Music'],'.primary-nav>a:nth-of-type(5)':['Échecs','Chess'],'.primary-nav>a:nth-of-type(6)':['Enseignants','Teachers'],'.pathway-menu summary':['Parcours','Learning paths'],'.pathway-menu a:nth-child(1)':['Citoyenneté','Citizenship'],'.pathway-menu a:nth-child(2)':['Environnement','Environment'],'.pathway-menu a:nth-child(3)':['Ressources responsables','Responsible resources'],'.pathway-menu a:nth-child(4)':['Mboka Numérique','Digital Mboka'],
  '.hero .eyebrow':['L’aventure commence ici','The adventure starts here'],'.hero h1':['La RDC comme tu ne l’as <em>jamais explorée.</em>','The DRC as you’ve <em>never explored it.</em>'],'.hero-copy>p':['Des rives du fleuve Congo aux sommets des Virunga, pars à la découverte d’un pays aux mille histoires.','From the Congo River to the peaks of the Virunga, discover a country of a thousand stories.'],'.hero-entry-points a:nth-child(1)':['Apprendre →','Learn →'],'.hero-entry-points a:nth-child(2)':['Jouer ★','Play ★'],'.hero-entry-points a:nth-child(3)':['Enseigner ✎','Teach ✎'],'.explore-more':['+ Explorer davantage','+ Explore more'],'.trust p':['<strong>Progression locale</strong><br>conservée sur cet appareil','<strong>Local progress</strong><br>kept on this device'],'.scroll-cue':['DÉFILE POUR EXPLORER ↓','SCROLL TO EXPLORE ↓'],
  '.daily-streak small':['SÉRIE ACTUELLE','CURRENT STREAK'],'.daily-label span':['✦ DÉCOUVERTE DU JOUR','✦ DAILY DISCOVERY'],'.week-heading small':['MES 7 DERNIERS JOURS','MY LAST 7 DAYS'],'.week-heading>span':['Objectif : 7 jours','Goal: 7 days'],
  '#explorer .section-heading .eyebrow':['Choisis ta route','Choose your path'],'#explorer h2':['Un pays, mille découvertes','One country, a thousand discoveries'],'#explorer .section-heading>p':['Chaque parcours contient des histoires courtes, des faits étonnants et des défis.','Every journey contains short stories, surprising facts and challenges.'],
  '#memory .eyebrow':['Jeu de mémoire','Memory game'],'#memory h2':['Les trésors<br>du Congo','Treasures<br>of the Congo'],'#memory .memory-copy>p':['Retourne les cartes et associe chaque trésor à sa signification. Trouve les six paires avec le moins de coups possible.','Turn over the cards and match each treasure with its meaning. Find all six pairs in as few moves as possible.'],
  '#provinces .eyebrow':['Carte d’exploration','Exploration map'],'#provinces h2':['26 provinces.<br>26 identités.','26 provinces.<br>26 identities.'],'#provinces .province-copy>p:first-of-type':['Découvre les chefs-lieux, paysages et repères de chaque province.','Discover the capitals, landscapes and landmarks of every province.'],'.map-header span':['CARTE INTERACTIVE','INTERACTIVE MAP'],'.map-header h3':['Voyage à travers la RDC','Journey across the DRC'],'.map-header>small':['CARTE SCHÉMATIQUE · NON DESTINÉE À LA NAVIGATION','SCHEMATIC MAP · NOT FOR NAVIGATION'],'#mapProvince':['Choisis une province','Choose a province'],'#mapDescription':['Sélectionne un point sur la carte pour découvrir son chef-lieu et un repère important.','Select a point on the map to discover its capital and an important landmark.'],'#openMapProfile':['Ouvrir le profil →','Open profile →'],
  '#sprint .eyebrow':['Nouveau jeu','New game'],'#sprint h2':['Le Sprint<br>des provinces','Province<br>Sprint'],'#sprint .sprint-heading p':['Associe chaque province à son chef-lieu. Dix manches, trois vies et un nouveau défi à chaque partie.','Match each province with its capital. Ten rounds, three lives and a new challenge every game.'],'.sprint-best span':['MEILLEUR SCORE','BEST SCORE'],'.sprint-best small':['points','points'],'.sprint-play>small':['QUEL EST LE CHEF-LIEU DE…','WHAT IS THE CAPITAL OF…'],
  '#quiz .quiz-intro .eyebrow':['Défi du jour','Daily challenge'],'#quiz .quiz-intro h2':['Prêt à tester tes connaissances ?','Ready to test your knowledge?'],'#quiz .quiz-intro>p':['Dix questions adaptées à ton niveau pour voyager à travers la RDC.','Ten age-appropriate questions for a journey across the DRC.'],'#levelPicker button:nth-child(1) strong':['Explorateur','Explorer'],'#levelPicker button:nth-child(1) small':['7–10 ANS','AGES 7–10'],'#levelPicker button:nth-child(2) strong':['Aventurier','Adventurer'],'#levelPicker button:nth-child(2) small':['11–14 ANS','AGES 11–14'],'#levelPicker button:nth-child(3) strong':['Maître','Master'],'#levelPicker button:nth-child(3) small':['15+ ANS','AGES 15+'],'.score-preview small':['MEILLEUR SCORE','BEST SCORE'],
  '#enseignants .eyebrow':['Espace enseignants','Teacher area'],'#enseignants h2':['Salisa Mboka Ekota<br>Kelasi','Bring Mboka<br>to the classroom.'],'#enseignants .teacher-intro>p':['Crée une fiche d’exercices prête à imprimer à partir des questions du jeu.','Create a printable exercise worksheet using questions from the game.'],'.builder-top small':['FICHE D’EXERCICES','EXERCISE WORKSHEET'],'.builder-top h3':['Générer une fiche d’exercices','Generate an exercise worksheet'],'#generateWorksheet':['↻ Nouvelle fiche','↻ New worksheet'],'#printWorksheet':['Imprimer la fiche','Print worksheet'],'.teacher-note':['L’impression permet aussi d’enregistrer la fiche au format PDF.','Printing also lets you save the worksheet as a PDF.'],
  '#pilot .eyebrow':['PROGRAMME PILOTE','PILOT PROGRAM'],'#pilot h2':['Salisa Mboka<br>Ekende Liboso','Help Mboka<br>grow.'],'#pilot .pilot-intro>p':['Un retour court et anonyme pour améliorer l’exactitude, la difficulté et le plaisir d’apprendre.','Short, anonymous feedback to improve accuracy, difficulty and learning enjoyment.'],'.pilot-privacy':['◈ Aucun nom, courriel ou compte demandé. Les réponses restent sur cet appareil jusqu’à leur exportation.','◈ No name, email or account requested. Responses stay on this device until exported.'],'.pilot-form-head small':['QUESTIONNAIRE · 2 MINUTES','SURVEY · 2 MINUTES'],'.pilot-form-head h3':['Ton expérience','Your experience'],'.pilot-grid label:nth-child(1)>span':['Je réponds comme','I am responding as'],'.pilot-grid label:nth-child(2)>span':['Mboka est facile à utiliser','Mboka is easy to use'],'.pilot-grid label:nth-child(3)>span':['Apprendre avec Mboka est amusant','Learning with Mboka is fun'],'.pilot-grid label:nth-child(4)>span':['J’ai appris quelque chose sur la RDC','I learned something about the DRC'],'.pilot-grid label:nth-child(5)>span':['Mon activité préférée','My favourite activity'],'.pilot-comment>span':['Une suggestion ? (facultatif)','A suggestion? (optional)'],'#pilotForm button[type="submit"]':['Enregistrer le retour','Save feedback'],'#exportFeedback':['Exporter en CSV','Export CSV'],'#clearFeedback':['Effacer','Clear'],
  'footer>p:nth-of-type(1)':['Apprendre. Explorer. Transmettre.','Learn. Explore. Share.'],'#privacyLink':['Confidentialité','Privacy'],
  '#profileTitle':['Kimi','Kimi'],'.profile-cover>span':['MON CARNET D’EXPLORATEUR','MY EXPLORER NOTEBOOK'],'.level-row small':['PROGRESSION GLOBALE','OVERALL PROGRESS'],'.profile-stats>div:nth-child(1) small':['MEILLEUR QUIZ','BEST QUIZ'],'.profile-stats>div:nth-child(2) small':['RECORD SPRINT','SPRINT RECORD'],'.profile-stats>div:nth-child(3) small':['PARCOURS','JOURNEYS'],'.badge-heading small':['MA COLLECTION','MY COLLECTION'],'.badge-heading h3':['Badges à débloquer','Badges to unlock'],'#printProgress':['Imprimer le rapport','Print report'],'#resetProgress':['Réinitialiser ma progression','Reset my progress']
};
Object.assign(uiCopy,{
  // Guided path (Trois étapes)
  '#guidedPath .eyebrow':['Parcours recommandé','Recommended path'],
  '#guidedPathTitle':['Trois étapes pour commencer.','Three simple steps to get started.'],
  '#guidedPath .guided-path-heading>p':['Une route simple pour découvrir Mboka sans devoir choisir parmi tous les modules.','A simple path to discover Mboka without having to choose between every module.'],
  '[data-guided-step="learn"] small':['APPRENDRE','LEARN'],
  '[data-guided-step="learn"] strong':['Découvrir un parcours','Discover a pathway'],
  '[data-guided-step="learn"] p':['Choisis un thème et ouvre une première leçon.','Choose a theme and open your first lesson.'],
  '[data-guided-step="play"] small':['JOUER','PLAY'],
  '[data-guided-step="play"] strong':['Tester tes connaissances','Test your knowledge'],
  '[data-guided-step="play"] p':['Réponds à dix questions adaptées à ton niveau.','Answer ten questions matched to your level.'],
  '[data-guided-step="teach"] small':['TRANSMETTRE','TEACH'],
  '[data-guided-step="teach"] strong':['Générer une fiche d’exercices','Generate an exercise sheet'],
  '[data-guided-step="teach"] p':['Transforme la découverte en fiche imprimable.','Turn what you’ve learned into a printable worksheet.'],

  // Pedagogical cards – common labels
  '.activity-pedagogy-card strong':['FICHE PÉDAGOGIQUE','TEACHING NOTE'],
  '.activity-pedagogy-card b:nth-of-type(1)':['Objectif :','Objective:'],
  '.activity-pedagogy-card b:nth-of-type(2)':['Compétence :','Skill:'],
  '.activity-pedagogy-card b:nth-of-type(3)':['Indicateur :','Indicator:'],
  '.activity-pedagogy-card b:nth-of-type(4)':['Preuve :','Evidence:'],
  '.activity-pedagogy-card b:nth-of-type(5)':['Statut :','Status:'],

  // Mission / Vision (polished)
  '#mission .eyebrow':['POURQUOI MBOKA','WHY MBOKA'],
  '#missionTitle':['Connaître son pays.<br>Mieux construire demain.','Know your country.<br>Build a better tomorrow.'],
  '.mission-heading>p':['Mboka relie culture, apprentissage et outils numériques pour accompagner les jeunes et les éducateurs de la RDC.','Mboka connects culture, learning and digital tools to support young people and educators in the DRC.'],
  '.vision-card>span':['01 · VISION','01 · VISION'],
  '.vision-card h3':['Une jeunesse qui connaît et comprend son pays.','A generation that knows and understands its country.'],
  '.vision-card p':['Permettre à chaque jeune Congolais de découvrir la RDC, ses cultures et son environnement grâce à une éducation numérique accessible, inclusive et contextualisée.','Enable every young Congolese person to discover the DRC — its cultures, landscapes and environment — through accessible, inclusive and contextualised digital education.'],
  '.mission-card:nth-child(2)>span':['02 · MISSION','02 · MISSION'],
  '.mission-card:nth-child(2) h3':['Transformer la découverte en apprentissage.','Turn discovery into real learning.'],
  '.mission-card:nth-child(2) p':['Proposer aux élèves et enseignants des contenus fiables, des activités éducatives et des outils simples pour apprendre, enseigner et mesurer les progrès.','Provide learners and teachers with reliable content, engaging activities and simple tools to learn, teach and track progress.'],
  '.commitment-list strong':['NOS ENGAGEMENTS','OUR COMMITMENTS'],
  '.commitment-list span:nth-of-type(1)':['Identité congolaise','Congolese identity'],
  '.commitment-list span:nth-of-type(2)':['Accès inclusif','Inclusive access'],
  '.commitment-list span:nth-of-type(3)':['Sécurité des enfants','Child safety'],
  '.commitment-list span:nth-of-type(4)':['Exactitude et validation','Accuracy and validation'],
  '.commitment-list span:nth-of-type(5)':['Impact mesurable','Measurable impact'],
  '#memoryCollectionLabel':['Collection','Collection'],'#memoryDifficultyLabel':['Difficulté','Difficulty'],
  '#quizModeLabel':['Mode','Mode'],'#quizTopicLabel':['Thème','Topic'],'#quizProvinceLabel':['Province','Province'],
  '.primary-nav>a:nth-of-type(7)':['Histoire','History'],
  '.module-nav a:nth-child(10)':['Histoire','History'],
  '.module-nav a:nth-child(11)':['Sources','Sources'],
  '#pilotMeasureEyebrow':['MESURE DU PILOTE','PILOT MEASUREMENT'],'#pilotMeasureTitle':['Pré-test et post-test','Pre-test and post-test'],'#pilotMeasureIntro':['Compare les apprentissages avec un code anonyme, sans nom ni courriel.','Compare learning outcomes with an anonymous code, without names or email addresses.'],'#pilotSchoolLabel':['Code de l’école','School code'],'#pilotLevelLabel':['Niveau','Level'],'#createPilotCode':['Créer un code anonyme','Create an anonymous code'],'#pilotExistingLabel':['Déjà inscrit ? Entre ton code pour le post-test','Already registered? Enter your code for the post-test'],'#usePilotCode':['Utiliser ce code','Use this code'],'#pilotCodeLabel':['Code à conserver :','Code to keep:'],'[data-pilot-phase="pre"]':['Pré-test','Pre-test'],'[data-pilot-phase="post"]':['Post-test','Post-test'],'#pilotResultLabel':['évaluations locales','local assessments'],'#exportPilotResults':['Exporter les résultats CSV','Export CSV results'],
  '.module-nav a:nth-child(1)':['Découvrir','Discover'],
  '.module-nav a:nth-child(2)':['Maths','Maths'],
  '.module-nav a:nth-child(3)':['Musique','Music'],
  '.module-nav a:nth-child(4)':['Échecs','Chess'],
  '.module-nav a:nth-child(5)':['Quiz','Quiz'],
  '.module-nav a:nth-child(6)':['Enseignants','Teachers'],
  '.module-nav a:nth-child(7)':['Citoyenneté','Citizenship'],
  '.module-nav a:nth-child(8)':['Environnement','Environment'],
  '.module-nav a:nth-child(9)':['Ressources','Resources'],
  '.skip-link':['Aller au contenu principal','Skip to main content'],
  '.map-header>small':['LIMITES DES 26 PROVINCES · CARTE PÉDAGOGIQUE','26 PROVINCE BOUNDARIES · EDUCATIONAL MAP'],
  '#mapSource':['Sources cartographiques : provinces — geoBoundaries COD ADM1, OpenStreetMap/Wambacher, ODbL 1.0; territoires — geoBoundaries COD ADM2, Référentiel Géographique Commun/OCHA RDC, CC BY 3.0 IGO. Catalogue recoupé avec la CAID et le PDL-145T. Limites indicatives à vocation pédagogique.','Map sources: provinces — geoBoundaries COD ADM1, OpenStreetMap/Wambacher, ODbL 1.0; territories — geoBoundaries COD ADM2, Common Geographic Repository/OCHA DRC, CC BY 3.0 IGO. Catalogue cross-checked with CAID and PDL-145T. Indicative boundaries for educational use.'],
  '#showProvinces':['26 provinces','26 provinces'],'#showTerritories':['145 territoires','145 territories'],'#territoryPicker span':['Choisir un territoire','Choose a territory'],'#territorySelect option':['Les 145 territoires…','The 145 territories…']
});

// Full English content for pedagogical cards (data-pedagogy-id 1..9)
const pedagogyEn = {
  1: `<strong>TEACHING NOTE</strong><span><b>Objective:</b> remember and explain one fact about the DRC.</span><span><b>Skill:</b> select information and restate it in your own words.</span><span><b>Indicator:</b> accurate reformulation without adding unverified information.</span><span><b>Evidence:</b> correct reformulation of the fact.</span><span><b>Status:</b> documented content · Mboka activity.</span>`,
  2: `<strong>TEACHING NOTE</strong><span><b>Objective:</b> explore a theme and connect several facts.</span><span><b>Skill:</b> observe, compare and restate information.</span><span><b>Indicator:</b> at least three accurate observations restated.</span><span><b>Evidence:</b> lesson opened, facts reformulated and a question asked.</span><span><b>Status:</b> Mboka educational adaptation.</span>`,
  3: `<strong>TEACHING NOTE</strong><div><span><b>Objective:</b> solve a contextualised problem by choosing a calculation strategy.</span><span><b>Skill:</b> use numbers, measurement and reasoning to justify a solution.</span><span><b>Indicator:</b> correct result and explained or verified method.</span><span><b>Evidence:</b> answer, intermediate calculations and result check.</span><span><b>Status:</b> Mboka educational adaptation · suitable for classroom use.</span></div>`,
  4: `<strong>TEACHING NOTE</strong><div><span><b>Objective:</b> identify and reproduce a short musical sequence.</span><span><b>Skill:</b> listen, read and interpret simple notes.</span><span><b>Indicator:</b> correct sequence reproduced with guidance if needed.</span><span><b>Evidence:</b> performed sequence and verbal description of the notes.</span><span><b>Status:</b> Mboka educational adaptation · suitable for classroom use.</span></div>`,
  5: `<strong>TEACHING NOTE</strong><div><span><b>Objective:</b> observe a position and choose a relevant move.</span><span><b>Skill:</b> analyse, calculate and explain a decision.</span><span><b>Indicator:</b> relevant move selected with a brief justification.</span><span><b>Evidence:</b> chosen move and short explanation of the idea.</span><span><b>Status:</b> Mboka educational adaptation · suitable for classroom use.</span></div>`,
  6: `<strong>TEACHING NOTE</strong><span><b>Objective:</b> memorise and connect information about the DRC.</span><span><b>Skill:</b> observe, compare and recall elements.</span><span><b>Indicator:</b> pairs found with an explained strategy.</span><span><b>Evidence:</b> successful pairs and justification of one association.</span><span><b>Status:</b> Mboka educational adaptation.</span>`,
  7: `<strong>TEACHING NOTE</strong><span><b>Objective:</b> locate a province and connect capital, landmark and context.</span><span><b>Skill:</b> read a map and compare territories.</span><span><b>Indicator:</b> province, capital and landmark correctly associated.</span><span><b>Evidence:</b> province profile opened and a comparison formulated.</span><span><b>Status:</b> Mboka educational adaptation.</span>`,
  8: `<strong>TEACHING NOTE</strong><span><b>Objective:</b> match each province with its capital.</span><span><b>Skill:</b> use geographic landmarks under time pressure.</span><span><b>Indicator:</b> accurate answers and improved recall strategy.</span><span><b>Evidence:</b> score, answer streak and explained correction.</span><span><b>Status:</b> Mboka educational adaptation.</span>`,
  9: `<strong>TEACHING NOTE</strong><span><b>Objective:</b> check and consolidate knowledge about the DRC.</span><span><b>Skill:</b> mobilise information and justify an answer.</span><span><b>Indicator:</b> score and correct explanation after each answer.</span><span><b>Evidence:</b> answers, final score and understood facts.</span><span><b>Status:</b> Mboka educational adaptation.</span>`
};
const pedagogyFrBackup = {};
function localizePedagogyCards(lang){
  document.querySelectorAll('[data-pedagogy-id]').forEach(card=>{
    const id = card.getAttribute('data-pedagogy-id');
    if(!pedagogyFrBackup[id]) pedagogyFrBackup[id] = card.innerHTML;
    if(lang === 'en' && pedagogyEn[id]) card.innerHTML = pedagogyEn[id];
    else if(pedagogyFrBackup[id]) card.innerHTML = pedagogyFrBackup[id];
  });
}

const htmlSelectors=new Set(['.hero h1','.trust p','#memory h2','#provinces h2','#sprint h2','#enseignants h2','#pilot h2','#missionTitle']);
function applyLanguage(lang){
  document.documentElement.lang=lang;localStorage.setItem('mbokaLang',lang);
  Object.entries(uiCopy).forEach(([selector,copy])=>{const el=document.querySelector(selector);if(!el)return;if(htmlSelectors.has(selector))el.innerHTML=copy[lang==='en'?1:0];else el.textContent=copy[lang==='en'?1:0]});
  const search=document.querySelector('#provinceSearch');search.placeholder=lang==='en'?'Search for a province…':'Chercher une province…';
  const comment=document.querySelector('#feedbackComment');if(comment)comment.placeholder=lang==='en'?'What you liked or what should change…':'Ce que tu as aimé ou ce qui devrait changer…';
  const school=document.querySelector('#pilotSchool');if(school)school.placeholder=lang==='en'?'E.g. SCHOOL-01':'Ex. ECOLE-01';
  const existingCode=document.querySelector('#pilotExistingCode');if(existingCode)existingCode.placeholder=lang==='en'?'E.g. SCHOOL-01-ABC':'Ex. ECOLE-01-ABC';
  const quizModeSelect=document.querySelector('#quizMode');if(quizModeSelect){quizModeSelect.options[0].textContent=lang==='en'?'General quiz':'Quiz général';quizModeSelect.options[1].textContent=lang==='en'?'Province quiz':'Quiz par province'}
  const quizTopicSelect=document.querySelector('#quizTopic');if(quizTopicSelect){const labels=lang==='en'?['All topics','Geography and provinces','Nature and science','Culture and history']:['Tous les thèmes','Géographie et provinces','Nature et sciences','Culture et histoire'];[...quizTopicSelect.options].forEach((option,index)=>option.textContent=labels[index])}
  const memoryCollection=document.querySelector('#memoryCollection');if(memoryCollection){const labels=lang==='en'?['Treasures of the Congo','Provinces and capitals','Nature and biodiversity','History and dates']:['Trésors du Congo','Provinces et chefs-lieux','Nature et biodiversité','Histoire et dates'];[...memoryCollection.options].forEach((option,index)=>option.textContent=labels[index])}
  const memoryDifficulty=document.querySelector('#memoryDifficulty');if(memoryDifficulty){const labels=lang==='en'?['Beginner · 4 pairs','Intermediate · 6 pairs','Advanced · 8 pairs']:['Débutant · 4 paires','Intermédiaire · 6 paires','Avancé · 8 paires'];[...memoryDifficulty.options].forEach((option,index)=>option.textContent=labels[index])}
  document.querySelector('#profileButton').setAttribute('aria-label',lang==='en'?'Open my profile':'Ouvrir mon profil');
  if(typeof updateSpeechControls==='function')updateSpeechControls();
  localizePedagogyCards(lang);
  localizeDynamic(lang);
}
let localizationBusy=false;
const languageSelect=document.querySelector('#languageSelect');languageSelect.value=localStorage.getItem('mbokaLang')||'fr';languageSelect.addEventListener('change',e=>{localStorage.setItem('mbokaLang',e.target.value);location.reload()});applyLanguage(languageSelect.value);

function setText(el,value){if(el&&el.textContent!==String(value))el.textContent=value}
function localizeDynamic(lang){
  if(lang!=='en'||localizationBusy)return;localizationBusy=true;const en=window.enContent,quizView=document.querySelector('#questionView'),customResultView=document.querySelector('#resultView'),memoryResultView=document.querySelector('#memoryComplete'),customQuiz=typeof quizMode!=='undefined'&&(quizMode!=='general'||quizTopic!=='all'),hideCustomQuiz=customQuiz&&quizView&&!quizView.hidden,hideCustomResult=customQuiz&&customResultView&&!customResultView.hidden,hideMemoryResult=memoryResultView&&!memoryResultView.hidden;if(hideCustomQuiz)quizView.hidden=true;if(hideCustomResult)customResultView.hidden=true;if(hideMemoryResult)memoryResultView.hidden=true;
  document.querySelectorAll('[data-journey]').forEach((card,i)=>{setText(card.querySelector('h3'),en.journeys[i].title);setText(card.querySelector('p'),en.journeys[i].text);setText(card.querySelector('small'),`JOURNEY ${String(i+1).padStart(2,'0')}`)});
  const regionNames={Toutes:'All',Ouest:'West',Centre:'Centre',Nord:'North',Est:'East',Sud:'South'};document.querySelectorAll('#regionFilters [data-region]').forEach(b=>setText(b,regionNames[b.dataset.region]));document.querySelectorAll('#provinceList [data-province]').forEach(card=>{const i=provinces.findIndex(p=>p[0]===card.dataset.province);if(i>=0)setText(card.querySelector('.province-region'),en.provinces[i][0])});
  if(typeof selectedMapProvince!=='undefined'&&selectedMapProvince>=0&&(typeof mapMode==='undefined'||mapMode!=='territories')){const p=provinces[selectedMapProvince],d=en.provinces[selectedMapProvince];setText(document.querySelector('#mapZone'),d[0]);setText(document.querySelector('#mapProvince'),p[0]);setText(document.querySelector('#mapDescription'),d[2]);setText(document.querySelector('#mapCapital'),p[1]);setText(document.querySelector('#mapLandmark'),d[1])}
  if(typeof current!=='undefined'&&document.querySelector('#questionView')&&!document.querySelector('#questionView').hidden){const enBank=quizLevel==='adventurer'?en.questions:en.levelQuestions[quizLevel],frBank=levelQuestionBanks[quizLevel],q=enBank[current],topics={PAYS:'COUNTRY',ANIMAUX:'ANIMALS',EAUX:'WATER',PROVINCES:'PROVINCES',LANGUES:'LANGUAGES',MUSIQUE:'MUSIC',NATURE:'NATURE',DRAPEAU:'FLAG',LACS:'LAKES',HYDROGRAPHIE:'HYDROGRAPHY',PATRIMOINE:'HERITAGE',GÉOGRAPHIE:'GEOGRAPHY',BIODIVERSITÉ:'BIODIVERSITY',RELIEF:'LANDFORMS',MINERAIS:'MINERALS',HISTOIRE:'HISTORY',CONSERVATION:'CONSERVATION',CULTURE:'CULTURE',FORÊTS:'FORESTS',VOLCANS:'VOLCANOES'};setText(document.querySelector('#questionNumber'),`QUESTION ${current+1} OF 10`);setText(document.querySelector('#questionTopic'),topics[frBank[current].topic]||frBank[current].topic);setText(document.querySelector('#questionText'),q.q);document.querySelectorAll('#answers .answer').forEach((b,i)=>{const prefix=String.fromCharCode(65+i)+'. ';if(b.textContent!==prefix+q.a[i])b.innerHTML=`<span>${prefix}</span>${q.a[i]}`});if(typeof answered!=='undefined'&&answered){const ok=document.querySelector('#answers .wrong')===null;const box=document.querySelector('#feedback'),key=`${quizLevel}-${current}-${ok}`;if(box.dataset.translation!==key){box.innerHTML=`<strong>${ok?'Well done! +100 points':'Not quite.'}</strong>${q.fact}`;box.dataset.translation=key}setText(document.querySelector('#nextButton'),current===9?'See my result →':'Next question →')}}
  const lesson=document.querySelector('#learningModal');if(lesson&&!lesson.hidden){const title=document.querySelector('#lessonTitle').textContent;const i=journeys.findIndex((j,n)=>j.title===title||en.journeys[n].title===title);if(i>=0){setText(document.querySelector('#lessonTitle'),en.journeys[i].title);setText(document.querySelector('#lessonLead'),en.journeys[i].lead);const facts=document.querySelector('#lessonFacts');if(facts.dataset.translation!==String(i)){facts.innerHTML=en.journeys[i].facts.map((f,n)=>`<div class="lesson-fact"><span>${n+1}</span><div><strong>${f[0]}</strong><p>${f[1]}</p></div></div>`).join('');facts.dataset.translation=String(i)}setText(document.querySelector('#lessonLabel'),'JOURNEY');setText(document.querySelector('#lessonNumber'),`JOURNEY ${String(i+1).padStart(2,'0')}`)}else{const p=provinces.find(x=>x[0]===title),facts=document.querySelector('#lessonFacts');if(p&&facts.dataset.encyclopedia!=='true'){setText(document.querySelector('#lessonLead'),`${p[1]} is the capital of ${p[0]} province.`);facts.innerHTML=`<div class="lesson-fact"><span>1</span><div><strong>Province</strong><p>${p[0]}</p></div></div><div class="lesson-fact"><span>2</span><div><strong>Capital</strong><p>${p[1]}</p></div></div><div class="lesson-fact"><span>3</span><div><strong>Coming soon</strong><p>The territories, landscapes, languages and cultures of this province will be added to its next notebook.</p></div></div>`;setText(document.querySelector('#lessonLabel'),'PROVINCE CARD');setText(document.querySelector('#lessonNumber'),'ONE OF 26 PROVINCES')}}setText(document.querySelector('#lessonQuiz'),'Take the quiz →')}
  if(lesson&&!lesson.hidden){const title=document.querySelector('#lessonTitle').textContent,pi=provinces.findIndex(p=>p[0]===title),facts=document.querySelector('#lessonFacts');if(pi>=0&&facts.dataset.encyclopedia!=='true'){const p=provinces[pi],d=en.provinces[pi],x=en.provinceProfiles[pi];setText(document.querySelector('#lessonLead'),`${p[1]} is the capital of ${p[0]} province. ${d[2]}`);facts.innerHTML=[['Broad region',d[0]],['Capital',p[1]],['Major towns',x[0]],['Languages spoken',x[1]],['Food traditions',x[2]],['Economy and resources',x[3]],['Famous places',x[4]]].map((f,n)=>`<div class="lesson-fact"><span>${n+1}</span><div><strong>${f[0]}</strong><p>${f[1]}</p></div></div>`).join('');facts.dataset.translation='rich-province';setText(document.querySelector('#lessonLabel'),'PROVINCE PROFILE');setText(document.querySelector('#lessonNumber'),`PROVINCE ${String(pi+1).padStart(2,'0')} OF 26`)}}
  document.querySelectorAll('.memory-card').forEach(card=>{const strong=card.querySelector('.memory-front strong'),small=card.querySelector('.memory-front small');if(en.memory[strong?.textContent])setText(strong,en.memory[strong.textContent]);if(en.memory[small?.textContent])setText(small,en.memory[small.textContent])});setText(document.querySelector('#memoryRestart'),'Shuffle and play again');
  [['#memoryMoves','MOVES '],['#memoryPairs','PAIRS '],['#memoryBest','BEST ']].forEach(([selector,label])=>{const el=document.querySelector(selector);if(el?.parentNode.firstChild?.nodeType===3)el.parentNode.firstChild.nodeValue=label});const memoryDone=document.querySelector('#memoryComplete');if(memoryDone&&!memoryDone.hidden){setText(document.querySelector('#memoryTitle'),memoryMoves<=9?'Exceptional memory!':'All six treasures found!');setText(document.querySelector('#memoryMessage'),`Game completed in ${memoryMoves} moves. Your best is ${localStorage.getItem('mbokaMemoryBest')}.`)}
  if(typeof sprintMode!=='undefined'&&sprintMode==='team')updateSprintStatus();else[['#sprintRound','ROUND '],['#sprintStreak','STREAK '],['#sprintLives','LIVES '],['#sprintScore','SCORE ']].forEach(([selector,label])=>{const el=document.querySelector(selector);if(el?.parentNode.querySelector('small'))setText(el.parentNode.querySelector('small'),label.trim())});
  if(typeof sprintAnswered!=='undefined'&&sprintAnswered&&(typeof sprintMode==='undefined'||sprintMode==='solo')){const correct=sprintDeck[sprintIndex][1];if(sprintFeedback.classList.contains('good'))setText(sprintFeedback,`Correct! ${correct} is the capital. Keep your streak going!`);else setText(sprintFeedback,`The correct answer was ${correct}.`);setText(sprintNext,(sprintIndex===9||sprintLives===0)?'See my result →':'Next round →')}
  const sprintResult=document.querySelector('#sprintResult');if(sprintResult&&!sprintResult.hidden&&(typeof sprintMode==='undefined'||sprintMode==='solo')){setText(document.querySelector('#sprintResultTitle'),sprintScore>=1200?'Province master!':sprintScore>=700?'Great journey!':'Keep exploring!');setText(document.querySelector('#sprintFinalScore'),`${sprintScore} points`);setText(document.querySelector('#sprintResultText'),`You completed ${sprintIndex+1} rounds. Play again: provinces and answers change every sprint.`);setText(document.querySelector('#sprintRestart'),'New sprint')}
  const quizResult=document.querySelector('#resultView');if(quizResult&&!quizResult.hidden){setText(document.querySelector('#resultTitle'),score>=8?'Remarkable explorer!':score>=5?'Great exploration!':'Your journey begins!');setText(document.querySelector('#resultMessage'),score>=8?'You already know the DRC very well. Keep exploring!':'Every question is a new discovery. Play again to improve your score.');setText(document.querySelector('#restartButton'),'Play again')}
  document.querySelectorAll('#badgeGrid .badge').forEach((badge,i)=>{if(!en.badges[i])return;setText(badge.querySelector('strong'),en.badges[i][0]);setText(badge.querySelector('p'),en.badges[i][1])});
  const rank=document.querySelector('#profileRank');if(rank){const p=Number(document.querySelector('#profilePercent').textContent.replace('%',''))||0;setText(rank,p>=90?'Master of the land':p>=60?'Great explorer':p>=25?'Curious explorer':'New explorer')}
  if(typeof renderWorksheet==='function')renderWorksheet();
  if(hideCustomQuiz)quizView.hidden=false;if(hideCustomResult)customResultView.hidden=false;if(hideMemoryResult)memoryResultView.hidden=false;localizationBusy=false;
}
window.refreshLanguage=()=>applyLanguage(languageSelect.value);
let lastDynamicSignature='';
function dynamicSignature(){return[typeof quizLevel==='undefined'?'':quizLevel,typeof current==='undefined'?'':current,typeof answered==='undefined'?'':answered,document.querySelector('#lessonTitle')?.textContent||'',document.querySelector('#learningModal')?.hidden,typeof sprintIndex==='undefined'?'':sprintIndex,typeof sprintAnswered==='undefined'?'':sprintAnswered,document.querySelector('#sprintResult')?.hidden,typeof memoryMatches==='undefined'?'':memoryMatches,document.querySelector('#profileModal')?.hidden].join('|')}
const languageObserver=new MutationObserver(()=>{if(languageSelect.value!=='en'||localizationBusy)return;const signature=dynamicSignature();if(signature===lastDynamicSignature)return;lastDynamicSignature=signature;requestAnimationFrame(()=>localizeDynamic('en'))});languageObserver.observe(document.body,{childList:true,subtree:true});
