const mathUnits=[
  {icon:'123',title:['Nombres et positions','Numbers and place value'],desc:['Lire, comparer et décomposer.','Read, compare and decompose.'],make:level=>{const values={explorer:[347,[300,40,7]],adventurer:[5284,[5000,200,80,4]],master:[47205,[40000,7000,200,5]]}[level],value=values[0],parts=values[1];return exercise(['Une bibliothèque classe ses livres.','A library is sorting its books.'],[`Quelle décomposition donne ${value} ?`,`Which decomposition makes ${value}?`],[parts.join(' + '),`${value-10} + 10`,`${Math.floor(value/10)} + ${value%10}`,`${value} + 1`],[`${value} est la somme de ses valeurs de position.`,`${value} is the sum of its place values.`])}},
  {icon:'+',title:['Addition et soustraction','Addition and subtraction'],desc:['Réunir, comparer et calculer.','Combine, compare and calculate.'],make:level=>{const [x,y]={explorer:[28,17],adventurer:[245,178],master:[1875,946]}[level],r=x+y;return exercise(['Un marché compte les produits vendus dans deux paniers.','A market counts products sold from two baskets.'],[`${x} produits plus ${y}, combien au total ?`,`${x} products plus ${y}: how many altogether?`],[r,r+10,r-5,r+1],[`${x} + ${y} = ${r}.`,`${x} + ${y} = ${r}.`])}},
  {icon:'×',title:['Multiplication et division','Multiplication and division'],desc:['Former des groupes égaux.','Make equal groups.'],make:level=>{const [x,y]={explorer:[6,4],adventurer:[14,12],master:[24,35]}[level],r=x*y;return exercise(['Des cahiers sont répartis en paquets identiques.','Exercise books are arranged in equal packs.'],[`${x} paquets de ${y} cahiers donnent combien de cahiers ?`,`How many books are in ${x} packs of ${y}?`],[r,x+y,r-x,r+y],[`${x} × ${y} = ${r}.`,`${x} × ${y} = ${r}.`])}},
  {icon:'½',title:['Fractions','Fractions'],desc:['Partager un tout équitablement.','Share a whole equally.'],make:level=>{const [num,den]={explorer:[1,4],adventurer:[3,8],master:[5,12]}[level];return exercise(['Une galette est partagée en parts égales.','A flatbread is divided into equal parts.'],[`${num} part${num>1?'s':''} sur ${den} représente quelle fraction ?`,`What fraction is ${num} part${num>1?'s':''} out of ${den}?`],[`${num}/${den}`,`${den}/${num}`,`${num}/${den+1}`,`${num+1}/${den}`],['Le numérateur compte les parts choisies; le dénominateur compte toutes les parts.','The numerator counts selected parts; the denominator counts all parts.'])}},
  {icon:'FC',title:['Décimaux et monnaie','Decimals and money'],desc:['Calculer des prix et rendre la monnaie.','Calculate prices and change.'],make:level=>{const [paid,price]={explorer:[5000,3200],adventurer:[10000,7350],master:[20000,12875]}[level],r=paid-price;return exercise(['Au marché, on calcule la monnaie à rendre.','At the market, change must be calculated.'],[`Un achat coûte ${price} FC. Tu paies ${paid} FC. Quelle monnaie reçois-tu ?`,`An item costs ${price} FC. You pay ${paid} FC. How much change do you receive?`],[`${r} FC`,`${r+500} FC`,`${price} FC`,`${paid+price} FC`],[`${paid} − ${price} = ${r} FC.`,`${paid} − ${price} = ${r} FC.`])}},
  {icon:'↔',title:['Mesures','Measurement'],desc:['Longueur, masse et capacité.','Length, mass and capacity.'],make:level=>{const meters={explorer:3,adventurer:12,master:25}[level],r=meters*100;return exercise(['On mesure une corde pour une activité scolaire.','A rope is measured for a school activity.'],[`${meters} mètres correspondent à combien de centimètres ?`,`How many centimetres are in ${meters} metres?`],[`${r} cm`,`${meters*10} cm`,`${r+100} cm`,`${meters} cm`],['Un mètre contient 100 centimètres.','One metre contains 100 centimetres.'])}},
  {icon:'◷',title:['Temps et durées','Time and duration'],desc:["Lire l’heure et planifier.",'Read time and plan.'],make:level=>{const [start,duration]={explorer:[8,2],adventurer:[9,3],master:[13,5]}[level],end=start+duration;return exercise(['Une activité commence et dure plusieurs heures.','An activity starts and lasts several hours.'],[`Elle commence à ${start} h et dure ${duration} h. À quelle heure finit-elle ?`,`It starts at ${start}:00 and lasts ${duration} hours. When does it end?`],[`${end} h`,`${end-1} h`,`${end+2} h`,`${duration} h`],[`${start} + ${duration} = ${end}.`,`${start} + ${duration} = ${end}.`])}},
  {icon:'△',title:['Géométrie','Geometry'],desc:['Formes, périmètres et surfaces.','Shapes, perimeter and area.'],make:level=>{const [w,h]={explorer:[4,3],adventurer:[7,5],master:[12,8]}[level],r=2*(w+h);return exercise(['Un jardin rectangulaire doit être entouré.','A rectangular garden needs a border.'],[`Le jardin mesure ${w} m sur ${h} m. Quel est son périmètre ?`,`The garden is ${w} m by ${h} m. What is its perimeter?`],[`${r} m`,`${w*h} m`,`${w+h} m`,`${r+2} m`],[`Périmètre = 2 × (${w} + ${h}) = ${r} m.`,`Perimeter = 2 × (${w} + ${h}) = ${r} m.`])}},
  {icon:'▥',title:['Données et graphiques','Data and graphs'],desc:['Lire, comparer et interpréter.','Read, compare and interpret.'],make:level=>{const data={explorer:[12,18,9],adventurer:[35,42,28],master:[125,148,97]}[level],max=Math.max(...data);return exercise(['Trois classes notent le nombre de livres lus.','Three classes record the number of books read.'],[`Les résultats sont ${data.join(', ')}. Quel est le plus grand ?`,`The results are ${data.join(', ')}. Which is greatest?`],[max,Math.min(...data),data[0],data.reduce((a,b)=>a+b,0)],[`${max} est la valeur la plus élevée.`,`${max} is the greatest value.`])}},
  {icon:'✦',title:['Problèmes du quotidien','Everyday problems'],desc:['Choisir les bonnes opérations.','Choose the right operations.'],make:level=>{const [groups,each,absent]={explorer:[3,8,2],adventurer:[6,24,7],master:[9,36,14]}[level],r=groups*each-absent;return exercise(['Des groupes participent à une visite éducative.','Groups are joining an educational visit.'],[`${groups} groupes de ${each} élèves sont inscrits, mais ${absent} sont absents. Combien participent ?`,`${groups} groups of ${each} learners registered, but ${absent} are absent. How many attend?`],[r,groups*each,r+absent,groups+each-absent],[`${groups} × ${each} − ${absent} = ${r}.`,`${groups} × ${each} − ${absent} = ${r}.`])}}
];
function exercise(context,q,a,why){return{context,q,a,correct:0,why}}
let mathLevel=localStorage.getItem('mbokaMathLevel')||'adventurer',mathUnit=0,mathAnswered=false;
const mathEnglish=()=>localStorage.getItem('mbokaLang')==='en';
function mathProgress(){try{const value=JSON.parse(localStorage.getItem(`mbokaMathProgress-${mathLevel}`)||'[]');return Array.isArray(value)?value.filter(n=>Number.isInteger(n)&&n>=0&&n<mathUnits.length):[]}catch{return[]}}
function renderMath(){const english=mathEnglish(),done=mathProgress();document.querySelector('#math .eyebrow').textContent=english?'Everyday mathematics':'Mathématiques du quotidien';document.querySelector('#math h2').innerHTML=english?'Calculate to<br>understand the world.':'Calculer pour<br>comprendre le monde.';document.querySelector('#mathIntro').textContent=english?'Ten short units using situations inspired by daily life in the DRC.':'Dix unités courtes avec des situations inspirées de la vie quotidienne en RDC.';document.querySelector('#mathProgressLabel').textContent=english?'MASTERED UNITS':'UNITÉS MAÎTRISÉES';document.querySelector('#mathProgressText').textContent=`${done.length} / ${mathUnits.length}`;document.querySelector('#mathProgressBar').style.width=`${done.length/mathUnits.length*100}%`;document.querySelectorAll('#mathLevelPicker button').forEach(b=>b.classList.toggle('active',b.dataset.mathLevel===mathLevel));document.querySelector('#mathUnitGrid').innerHTML=mathUnits.map((u,i)=>`<button class="math-unit ${done.includes(i)?'done':''}" data-math-unit="${i}"><span>${u.icon}</span><strong>${u.title[english?1:0]}</strong><p>${u.desc[english?1:0]}</p><small>${done.includes(i)?(english?'MASTERED ✓':'MAÎTRISÉE ✓'):`${english?'UNIT':'UNITÉ'} ${String(i+1).padStart(2,'0')}`}</small></button>`).join('')}
function shuffledAnswers(exerciseData){const answers=exerciseData.a.map((value,index)=>({value:String(value),correct:index===exerciseData.correct}));for(let i=answers.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[answers[i],answers[j]]=[answers[j],answers[i]]}return answers}
function showMathExercise(){const english=mathEnglish(),unit=mathUnits[mathUnit],current=unit.make(mathLevel),answers=shuffledAnswers(current);mathAnswered=false;document.querySelector('#mathChallenge').hidden=false;document.querySelector('#mathUnitNumber').textContent=`${english?'UNIT':'UNITÉ'} ${String(mathUnit+1).padStart(2,'0')}`;document.querySelector('#mathUnitTitle').textContent=unit.title[english?1:0];document.querySelector('#mathContext').textContent=current.context[english?1:0];document.querySelector('#mathQuestion').textContent=current.q[english?1:0];document.querySelector('#mathFeedback').textContent='';document.querySelector('#mathFeedback').className='math-feedback';document.querySelector('#mathNext').hidden=true;document.querySelector('#mathNext').textContent=english?'Try again →':'Recommencer →';document.querySelector('#mathOptions').innerHTML=answers.map((a,i)=>`<button type="button" data-correct="${a.correct}"><span>${String.fromCharCode(65+i)}.</span> ${a.value}</button>`).join('');document.querySelector('#mathOptions').dataset.why=current.why[english?1:0];document.querySelector('#mathChallenge').scrollIntoView({behavior:'smooth',block:'center'})}
document.querySelector('#mathUnitGrid').addEventListener('click',event=>{const button=event.target.closest('[data-math-unit]');if(!button)return;mathUnit=Number(button.dataset.mathUnit);showMathExercise()});
document.querySelector('#mathLevelPicker').addEventListener('click',event=>{const button=event.target.closest('[data-math-level]');if(!button)return;mathLevel=button.dataset.mathLevel;localStorage.setItem('mbokaMathLevel',mathLevel);document.querySelector('#mathChallenge').hidden=true;renderMath()});
document.querySelector('#mathOptions').addEventListener('click',event=>{const button=event.target.closest('button');if(!button||mathAnswered)return;mathAnswered=true;const good=button.dataset.correct==='true',feedback=document.querySelector('#mathFeedback');document.querySelectorAll('#mathOptions button').forEach(b=>{b.disabled=true;if(b.dataset.correct==='true')b.classList.add('correct')});if(!good)button.classList.add('wrong');feedback.classList.add(good?'good':'bad');feedback.textContent=`${good?(mathEnglish()?'Correct!':'Correct !'):(mathEnglish()?'Not quite.':'Pas encore.')} ${document.querySelector('#mathOptions').dataset.why}`;if(good){const done=new Set(mathProgress());done.add(mathUnit);localStorage.setItem(`mbokaMathProgress-${mathLevel}`,JSON.stringify([...done].sort((a,b)=>a-b)));renderMath()}document.querySelector('#mathNext').hidden=false});
document.querySelector('#mathNext').addEventListener('click',showMathExercise);document.querySelector('#mathClose').addEventListener('click',()=>{document.querySelector('#mathChallenge').hidden=true});renderMath();
