const musicSections=[
  {title:['Notes avec étiquettes','Labeled notes'],instruction:['Écoute puis rejoue les cinq notes. Les noms restent visibles.','Listen, then replay the five notes. Labels remain visible.'],notes:['C','D','E','D','C'],labels:true,staff:false,black:false},
  {title:['Lire une partition','Read sheet music'],instruction:['Observe la position des notes sur la portée, puis joue-les dans l’ordre.','Observe each note position on the staff, then play them in order.'],notes:['C','E','G','F','D'],labels:true,staff:true,black:false},
  {title:['Jouer les touches blanches','Play white keys'],instruction:['Les étiquettes disparaissent : utilise la position des touches et ton oreille.','Labels are hidden: use key positions and your ear.'],notes:['C','E','G','E','C'],labels:false,staff:false,black:false},
  {title:['Découvrir les touches noires','Play black keys'],instruction:['Joue une courte suite avec des dièses, les notes entre deux touches blanches.','Play a short pattern with sharps, the notes between white keys.'],notes:['C','C#','D#','F','G#'],labels:true,staff:false,black:true}
];
const musicFrequencies={C:261.63,'C#':277.18,D:293.66,'D#':311.13,E:329.63,F:349.23,'F#':369.99,G:392,'G#':415.3,A:440,'A#':466.16,B:493.88};
const whiteNotes=['C','D','E','F','G','A','B'],blackPositions={'C#':10.3,'D#':24.6,'F#':53.2,'G#':67.5,'A#':81.8};
let musicSection=0,musicStep=0,musicLocked=false,musicAudioContext;
const musicEnglish=()=>localStorage.getItem('mbokaLang')==='en';
const musicIsiOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const musicFileNames={C:'C','C#':'Cs',D:'D','D#':'Ds',E:'E',F:'F','F#':'Fs',G:'G','G#':'Gs',A:'A','A#':'As',B:'B'};
const musicFilePlayer=musicIsiOS?new Audio('./music-C.wav'):null;
if(musicFilePlayer){musicFilePlayer.preload='auto';musicFilePlayer.playsInline=true;musicFilePlayer.load()}
function musicCompleted(){try{const value=JSON.parse(localStorage.getItem('mbokaMusicProgress')||'[]');return Array.isArray(value)?value.filter(n=>Number.isInteger(n)&&n>=0&&n<musicSections.length):[]}catch{return[]}}
function highlightMusicKey(note){const key=document.querySelector(`[data-music-note="${note}"]`);key?.classList.add('playing');setTimeout(()=>key?.classList.remove('playing'),420)}
function playMusicFile(note){try{musicFilePlayer.pause();musicFilePlayer.src=`./music-${musicFileNames[note]}.wav`;musicFilePlayer.currentTime=0;const playback=musicFilePlayer.play();highlightMusicKey(note);playback?.catch(()=>{const feedback=document.querySelector('#musicGameFeedback');feedback.textContent=musicEnglish()?'iPhone blocked playback. Turn off silent mode and tap the key again.':'L’iPhone a bloqué la lecture. Désactivez le mode silencieux puis retouchez la touche.';feedback.className='music-game-feedback bad'});return true}catch{return false}}
function playMusicNote(note){if(musicIsiOS)return playMusicFile(note);const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return false;try{musicAudioContext=musicAudioContext||new AudioContext();if(musicAudioContext.state!=='running')musicAudioContext.resume();const oscillator=musicAudioContext.createOscillator(),gain=musicAudioContext.createGain();oscillator.type='triangle';oscillator.frequency.value=musicFrequencies[note];gain.gain.setValueAtTime(.0001,musicAudioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.38,musicAudioContext.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,musicAudioContext.currentTime+.5);oscillator.connect(gain).connect(musicAudioContext.destination);oscillator.start(0);oscillator.stop(musicAudioContext.currentTime+.52);highlightMusicKey(note);return true}catch{return false}}
function renderMusicList(){const english=musicEnglish(),done=musicCompleted();document.querySelector('#musicSectionList').innerHTML=musicSections.map((section,index)=>`<button class="music-section-button ${index===musicSection?'active':''} ${done.includes(index)?'done':''}" data-music-section="${index}"><span>${index+1}</span><span><small>${english?'SECTION':'SECTION'} ${index+1}</small><strong>${section.title[english?1:0]}</strong></span><span>${done.includes(index)?'✓':''}</span></button>`).join('');document.querySelector('#musicGameProgress').textContent=english?`${done.length} / 4 sections mastered`:`${done.length} / 4 sections maîtrisées`;document.querySelector('#musicGameProgressBar').style.width=`${done.length/4*100}%`}
function renderMusicKeyboard(){const section=musicSections[musicSection],english=musicEnglish(),keyboard=document.querySelector('#musicKeyboard');keyboard.innerHTML=whiteNotes.map(note=>`<button class="piano-key white" type="button" data-music-note="${note}" aria-label="${note}">${section.labels?note:''}</button>`).join('')+(section.black?Object.entries(blackPositions).map(([note,left])=>`<button class="piano-key black" style="left:${left}%" type="button" data-music-note="${note}" aria-label="${note}">${section.labels?note.replace('#','♯'):''}</button>`).join(''):'');keyboard.setAttribute('aria-label',english?'Interactive musical keyboard':'Clavier musical interactif')}
function renderStaff(){const section=musicSections[musicSection],staff=document.querySelector('#musicStaff'),positions={C:94,D:87,E:80,F:73,G:66,A:59,B:52};staff.hidden=!section.staff;document.querySelector('#staffNotes').innerHTML=section.staff?section.notes.map((note,index)=>`<i class="staff-note" style="left:${12+index*18}%;top:${positions[note]||70}px" title="${note}">${note}</i>`).join(''):''}
function renderMusicSequence(){const section=musicSections[musicSection];document.querySelector('#musicSequence').innerHTML=section.notes.map((note,index)=>`<span class="${index<musicStep?'done':index===musicStep?'current':''}">${section.labels||section.staff?note.replace('#','♯'):'♪'}</span>`);document.querySelector('#musicStepScore').textContent=`${musicStep} / ${section.notes.length}`}
function resetMusicExercise(){musicStep=0;musicLocked=false;const english=musicEnglish(),section=musicSections[musicSection];document.querySelector('#musicSectionNumber').textContent=`SECTION ${musicSection+1}`;document.querySelector('#musicSectionTitle').textContent=section.title[english?1:0];document.querySelector('#musicInstruction').textContent=section.instruction[english?1:0];document.querySelector('#musicGameFeedback').textContent='';document.querySelector('#musicGameFeedback').className='music-game-feedback';document.querySelector('#musicListen').textContent=english?'Listen':'Écouter';document.querySelector('#musicRestart').textContent=english?'Restart':'Recommencer';renderMusicList();renderMusicKeyboard();renderStaff();renderMusicSequence()}
function completeMusicSection(){const done=new Set(musicCompleted());done.add(musicSection);localStorage.setItem('mbokaMusicProgress',JSON.stringify([...done].sort((a,b)=>a-b)));const feedback=document.querySelector('#musicGameFeedback');feedback.textContent=musicEnglish()?'Well done! Section mastered.':'Bravo ! Section maîtrisée.';feedback.className='music-game-feedback good';renderMusicList()}
document.querySelector('#musicKeyboard').addEventListener('click',event=>{const key=event.target.closest('[data-music-note]');if(!key||musicLocked)return;const note=key.dataset.musicNote,expected=musicSections[musicSection].notes[musicStep];if(!playMusicNote(note)){const feedback=document.querySelector('#musicGameFeedback');feedback.textContent=musicEnglish()?'Sound is blocked. Turn up media volume, then tap a key again.':'Le son est bloqué. Montez le volume multimédia, puis touchez encore une touche.';feedback.className='music-game-feedback bad';return}if(note===expected){musicStep++;document.querySelector('#musicGameFeedback').textContent='';if(musicStep===musicSections[musicSection].notes.length){musicLocked=true;completeMusicSection()}renderMusicSequence()}else{musicStep=0;const feedback=document.querySelector('#musicGameFeedback');feedback.textContent=musicEnglish()?`Try again. The next note was ${expected.replace('#',' sharp')}.`:`Recommence. La prochaine note était ${expected.replace('#',' dièse')}.`;feedback.className='music-game-feedback bad';renderMusicSequence()}});
document.querySelector('#musicSectionList').addEventListener('click',event=>{const button=event.target.closest('[data-music-section]');if(!button)return;musicSection=Number(button.dataset.musicSection);resetMusicExercise()});
document.querySelector('#musicListen').addEventListener('click',async()=>{if(musicLocked)return;musicLocked=true;const notes=musicSections[musicSection].notes;if(!playMusicNote(notes[0])){musicLocked=false;const feedback=document.querySelector('#musicGameFeedback');feedback.textContent=musicEnglish()?'Sound is blocked. Turn up media volume, then tap Listen again.':'Le son est bloqué. Montez le volume multimédia, puis touchez encore Écouter.';feedback.className='music-game-feedback bad';return}await new Promise(resolve=>setTimeout(resolve,560));for(const note of notes.slice(1)){playMusicNote(note);await new Promise(resolve=>setTimeout(resolve,560))}musicLocked=false});document.querySelector('#musicRestart').addEventListener('click',resetMusicExercise);
function localizeMusicHeader(){const english=musicEnglish();document.querySelector('#musicLab .eyebrow').textContent=english?'Music laboratory':'Laboratoire musical';document.querySelector('#musicLab h2').innerHTML=english?'Listen, read,<br>then play.':'Écouter, lire,<br>puis jouer.';document.querySelector('#musicGameIntro').textContent=english?'Four steps to discover notes, read a staff and play short original melodies.':'Quatre étapes pour découvrir les notes, lire une portée et jouer de courtes mélodies originales.';document.querySelector('#musicGameNote').textContent=english?'The melodies in this exercise are original. Sound is produced on the device and no audio data is recorded.':'Les mélodies de cet exercice sont originales. Le son est produit sur l’appareil et aucune donnée audio n’est enregistrée.'}
localizeMusicHeader();resetMusicExercise();
