(()=>{
  const $=selector=>document.querySelector(selector),storageKey='mbokaPilotTests',english=localStorage.getItem('mbokaLang')==='en';
  let learnerCode='',phase='pre',questionIndex=0,score=0,deck=[];
  const copy={saved:english?'Result saved on this device.':'Résultat enregistré sur cet appareil.',keep:english?'Complete at least three Mboka sessions, then return with the same code for the post-test.':'Réalise au moins trois séances Mboka, puis reviens avec le même code pour le post-test.',invalid:english?'Enter a valid anonymous code.':'Entre un code anonyme valide.',missing:english?'No pre-test was found for this code on this device.':'Aucun pré-test associé à ce code n’a été trouvé sur cet appareil.',ready:english?'Code recognized. The post-test is ready.':'Code reconnu. Le post-test est prêt.',pre:'PRE-TEST',post:'POST-TEST'};
  function load(){try{return JSON.parse(localStorage.getItem(storageKey)||'[]')}catch{return[]}}
  function updateCount(){const count=load().length;$('#pilotResultCount').textContent=count;$('#exportPilotResults').disabled=!count}
  function finish(){const results=load();results.push({timestamp:new Date().toISOString(),school:$('#pilotSchool').value.trim(),learner_code:learnerCode,phase,level:$('#pilotLevel').value,score,total:deck.length});localStorage.setItem(storageKey,JSON.stringify(results));$('#pilotTestProgress').textContent=copy.saved;$('#pilotTestQuestion').textContent=`${phase==='pre'?(english?'Pre-test':'Pré-test'):(english?'Post-test':'Post-test')} ${english?'completed':'terminé'} : ${score}/${deck.length}`;$('#pilotTestAnswers').innerHTML='';$('#pilotTestStatus').textContent=phase==='pre'?copy.keep:'';updateCount()}
  function showQuestion(){if(questionIndex===deck.length){finish();return}const question=deck[questionIndex];$('#pilotTestProgress').textContent=`${copy[phase]} · ${questionIndex+1}/${deck.length}`;$('#pilotTestQuestion').textContent=question.q;$('#pilotTestAnswers').innerHTML=question.a.map((answer,index)=>`<button class="answer" data-pilot-answer="${index}">${answer}</button>`).join('');$('#pilotTestStatus').textContent=''}
  function start(nextPhase){phase=nextPhase;questionIndex=0;score=0;const level=$('#pilotLevel').value,bank=english?(level==='adventurer'?window.enContent.questions:window.enContent.levelQuestions[level]):levelQuestionBanks[level];deck=bank.slice(0,5);document.querySelectorAll('[data-pilot-phase]').forEach(button=>button.classList.toggle('active',button.dataset.pilotPhase===phase));$('#pilotTest').hidden=false;showQuestion()}
  function revealCode(){$('#pilotLearnerCode').textContent=learnerCode;$('#pilotCodeBox').hidden=false;$('#pilotCodeStatus').textContent=''}
  $('#createPilotCode').addEventListener('click',()=>{const school=($('#pilotSchool').value.trim().toUpperCase().replace(/[^A-Z0-9-]/g,'')||'MBOKA').slice(0,12);learnerCode=`${school}-${crypto.getRandomValues(new Uint16Array(1))[0].toString(36).toUpperCase().padStart(3,'0')}`;revealCode();start('pre')});
  $('#usePilotCode').addEventListener('click',()=>{const candidate=$('#pilotExistingCode').value.trim().toUpperCase();if(!/^[A-Z0-9-]{5,24}$/.test(candidate)){$('#pilotCodeStatus').textContent=copy.invalid;return}const pre=load().find(result=>result.learner_code===candidate&&result.phase==='pre');if(!pre){$('#pilotCodeStatus').textContent=copy.missing;return}learnerCode=candidate;$('#pilotSchool').value=pre.school;$('#pilotLevel').value=pre.level;revealCode();$('#pilotCodeStatus').textContent=copy.ready;start('post')});
  $('#pilotTestAnswers').addEventListener('click',event=>{const button=event.target.closest('[data-pilot-answer]');if(!button)return;if(Number(button.dataset.pilotAnswer)===deck[questionIndex].correct)score++;questionIndex++;showQuestion()});
  document.querySelectorAll('[data-pilot-phase]').forEach(button=>button.addEventListener('click',()=>{if(!learnerCode)return;if(button.dataset.pilotPhase==='post'&&!load().some(result=>result.learner_code===learnerCode&&result.phase==='pre')){$('#pilotTestStatus').textContent=copy.missing;return}start(button.dataset.pilotPhase)}));
  $('#exportPilotResults').addEventListener('click',()=>{const data=load(),columns=['timestamp','school','learner_code','phase','level','score','total','pre_score','post_score','gain'];const rows=data.map(result=>{const paired=data.filter(item=>item.learner_code===result.learner_code&&item.level===result.level),pre=paired.find(item=>item.phase==='pre'),post=[...paired].reverse().find(item=>item.phase==='post');return {...result,pre_score:pre?.score??'',post_score:post?.score??'',gain:pre&&post?post.score-pre.score:''}});const csv=[columns.join(','),...rows.map(row=>columns.map(column=>`"${String(row[column]??'').replace(/"/g,'""')}"`).join(','))].join('\r\n'),anchor=document.createElement('a');anchor.href=URL.createObjectURL(new Blob(['\uFEFF',csv],{type:'text/csv'}));anchor.download='mboka-pilot-results.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(anchor.href),0)});
  updateCount();
})();
