(()=>{
  const sources=[
    {tag:['ADMINISTRATION','ADMINISTRATION'],title:['Limites des provinces et territoires','Province and territory boundaries'],text:['Jeux de données géographiques ouverts utilisés pour représenter les 26 provinces et les 145 territoires.','Open geographic datasets used to represent the 26 provinces and 145 territories.'],name:'geoBoundaries COD ADM1/ADM2',url:'https://www.geoboundaries.org/countryDownloads.html'},
    {tag:['PATRIMOINE NATUREL','NATURAL HERITAGE'],title:['Sites naturels de la RDC','Natural sites in the DRC'],text:['Liste officielle, dates d’inscription et rapports de conservation des cinq biens naturels congolais inscrits.','Official list, inscription dates and conservation reports for the five listed Congolese natural properties.'],name:['UNESCO · RDC','UNESCO · DRC'],url:'https://whc.unesco.org/fr/etatsparties/cd'},
    {tag:['HISTOIRE POLITIQUE','POLITICAL HISTORY'],title:['Présidents et indépendance','Presidents and independence'],text:['Archives institutionnelles sur les anciens présidents et les symboles historiques de la République.','Institutional records concerning former presidents and historical symbols of the Republic.'],name:['Présidence de la RDC','Presidency of the DRC'],url:'https://www.presidence.cd/anciens-presidents'},
    {tag:['DROIT ET CITOYENNETÉ','LAW AND CITIZENSHIP'],title:['Constitution de 2006','2006 Constitution'],text:['Texte constitutionnel et exposé des motifs encadrant les institutions de la Troisième République.','Constitutional text and explanatory memorandum framing the institutions of the Third Republic.'],name:'Leganet · Journal officiel',url:'https://www.leganet.cd/Legislation/Droit%20Public/Constitution.2011.pdf'},
    {tag:['HISTOIRE COLONIALE','COLONIAL HISTORY'],title:['Archives de la colonisation','Colonial archives'],text:['Repères et fonds documentaires sur l’État indépendant du Congo et le Congo belge.','Reference points and archival holdings on the Congo Free State and Belgian Congo.'],name:'AfricaMuseum · Archives',url:'https://www.africamuseum.be/en/research/news/guide_archives_colonisation'},
    {tag:['NATIONS UNIES','UNITED NATIONS'],title:['Noms et statut international','Names and international status'],text:['Repères des Nations Unies sur l’adhésion du pays et le retour au nom République démocratique du Congo en 1997.','United Nations records on the country’s membership and restoration of the name Democratic Republic of the Congo in 1997.'],name:['Nations Unies','United Nations'],url:'https://www.un.org/en/about-us/member-states/democratic-republic-of-the-congo'},
    {tag:['SYSTÈME ÉDUCATIF','EDUCATION SYSTEM'],title:['Niveaux et programmes nationaux','National levels and curricula'],text:['Références officielles sur le primaire, le cycle terminal de l’éducation de base, les humanités et l’approche par situations.','Official references on primary education, the terminal basic-education cycle, humanities, and the situation-based approach.'],name:['MINEDU-NC · Programmes nationaux','MINEDU-NC · National curricula'],url:'https://edu-nc.gouv.cd/programmes-nationaux'},
    {tag:['CITOYENNETÉ NUMÉRIQUE','DIGITAL CITIZENSHIP'],title:['Code du numérique de la RDC','DRC Digital Code'],text:['Ordonnance-loi n° 23/010 du 13 mars 2023 portant Code du numérique, utilisée comme référence du module Mboka Numérique.','Ordinance-Law No. 23/010 of 13 March 2023 establishing the Digital Code, used as the reference for Digital Mboka.'],name:['ANAPI · Texte du Code','ANAPI · Digital Code text'],url:'https://anapi.cd/services-financiers-pilier-global'}
  ];
  const english=localStorage.getItem('mbokaLang')==='en',n=english?1:0,value=item=>Array.isArray(item)?item[n]:item;
  if(english){document.querySelector('#sourcesEyebrow').textContent='SOURCES AND METHOD';document.querySelector('#sourcesTitle').textContent='Understand where the information comes from.';document.querySelector('#sourcesIntro').textContent='Mboka distinguishes institutional data, documented content, and its pedagogical adaptations.'}
  document.querySelector('#sourceStatus').innerHTML=english?'<span>✓ Institutional or documented source</span><span>◇ Mboka pedagogical adaptation</span>':'<span>✓ Source institutionnelle ou documentée</span><span>◇ Adaptation pédagogique Mboka</span>';
  document.querySelector('#sourceGrid').innerHTML=sources.map(source=>`<article class="source-card"><small>${value(source.tag)}</small><h3>${value(source.title)}</h3><p>${value(source.text)}</p><a href="${source.url}" target="_blank" rel="noopener noreferrer">${value(source.name)} ↗</a></article>`).join('');
  document.querySelector('#sourceNote').textContent=english?'A source supports a specific fact; it does not automatically validate every cultural description. Educators can use the pedagogical review form to propose corrections or stronger references.':'Une source soutient un fait précis; elle ne valide pas automatiquement toutes les descriptions culturelles. Les éducateurs peuvent utiliser le formulaire de revue pédagogique pour proposer une correction ou une référence plus solide.';
})();
