(()=>{
  const $=selector=>document.querySelector(selector),english=localStorage.getItem('mbokaLang')==='en',sessionKey='mbokaTeacherSession';
  const provinces=['Bas-Uélé','Équateur','Haut-Katanga','Haut-Lomami','Haut-Uélé','Ituri','Kasaï','Kasaï-Central','Kasaï-Oriental','Kinshasa','Kongo-Central','Kwango','Kwilu','Lomami','Lualaba','Mai-Ndombe','Maniema','Mongala','Nord-Kivu','Nord-Ubangi','Sankuru','Sud-Kivu','Sud-Ubangi','Tanganyika','Tshopo','Tshuapa'];
  const copy=english?{button:'Teacher account',eyebrow:'TEACHER AREA · BETA',title:'Your secure teaching workspace.',intro:'Invitation-only access. Learners continue using Mboka without accounts.',email:'Professional email',send:'Send my secure link',help:'No password. The link is sent only to invited teachers.',connected:'SIGNED IN',logout:'Sign out',name:'Display name',school:'School',province:'Education province',cycle:'Main cycle',subjects:'Subjects',save:'Save my profile',tools:'Open teacher tools',sent:'Check your inbox. If this address was invited, a secure link has been sent.',unavailable:'Teacher accounts are being configured. Public Mboka and all local teacher tools remain available.',error:'The request could not be completed. Please try again.',saved:'Profile saved.',roles:{teacher:'Teacher',coordinator:'Coordinator',admin:'Administrator'}}:{button:'Compte enseignant',eyebrow:'ESPACE ENSEIGNANT · BÊTA',title:'Ton espace pédagogique sécurisé.',intro:'Accès sur invitation. Les élèves continuent à utiliser Mboka sans compte.',email:'Adresse professionnelle',send:'Recevoir mon lien sécurisé',help:'Aucun mot de passe. Le lien est envoyé uniquement aux enseignants invités.',connected:'CONNECTÉ',logout:'Se déconnecter',name:'Nom affiché',school:'Établissement',province:'Province éducationnelle',cycle:'Cycle principal',subjects:'Disciplines',save:'Enregistrer mon profil',tools:'Ouvrir les outils enseignants',sent:'Consultez votre messagerie. Si cette adresse a été invitée, un lien sécurisé a été envoyé.',unavailable:'Les comptes enseignants sont en cours de configuration. Mboka public et tous les outils enseignants locaux restent disponibles.',error:'La demande n’a pas pu aboutir. Réessayez.',saved:'Profil enregistré.',roles:{teacher:'Enseignant',coordinator:'Coordinateur',admin:'Administrateur'}};
  const text={teacherAccountButton:'button',teacherAccountEyebrow:'eyebrow',teacherAccountTitle:'title',teacherAccountIntro:'intro',teacherEmailLabel:'email',teacherLoginButton:'send',teacherLoginHelp:'help',teacherConnectedLabel:'connected',teacherLogout:'logout',teacherSchoolLabel:'school',teacherProvinceLabel:'province',teacherCycleLabel:'cycle',teacherSubjectsLabel:'subjects',teacherSaveProfile:'save',teacherOpenTools:'tools'};Object.entries(text).forEach(([id,key])=>{const el=document.getElementById(id);if(el)el.textContent=copy[key]});
  const nameLabel=document.createElement('label');nameLabel.innerHTML=`<span>${copy.name}</span><input id="teacherDisplayName" maxlength="80" autocomplete="name" required placeholder="${english?'E.g. Thelly Mulongo':'Ex. Thelly Mulongo'}">`;$('.teacher-profile-grid').prepend(nameLabel);
  const adminPanel=document.createElement('section');adminPanel.id='teacherAdminPanel';adminPanel.className='teacher-admin-panel';adminPanel.hidden=true;adminPanel.innerHTML=`<div class="teacher-admin-heading"><div><small>ADMINISTRATION</small><h3>${english?'Manage teachers':'Gérer les enseignants'}</h3></div><button type="button" id="refreshInvitations" class="button secondary">${english?'Refresh':'Actualiser'}</button></div><form id="teacherInvitationForm" class="teacher-invitation-form"><label><span>${english?'Teacher email':'Adresse de l’enseignant'}</span><input id="invitationEmail" type="email" maxlength="254" required placeholder="enseignant@ecole.cd"></label><label><span>${english?'Role':'Rôle'}</span><select id="invitationRole"><option value="teacher">${english?'Teacher':'Enseignant'}</option><option value="coordinator">${english?'Coordinator':'Coordinateur'}</option><option value="admin">${english?'Administrator':'Administrateur'}</option></select></label><button class="button primary" type="submit">${english?'Add invitation':'Ajouter l’invitation'}</button></form><p class="teacher-admin-status" id="teacherAdminStatus" aria-live="polite"></p><div class="teacher-invitation-list" id="teacherInvitationList"></div>`;$('.teacher-account-sheet').append(adminPanel);
  $('#teacherProvince').innerHTML=provinces.map(name=>`<option value="${name}">${name}</option>`).join('');
  function getSession(){try{return JSON.parse(sessionStorage.getItem(sessionKey)||'null')}catch{return null}}
  function setSession(value){if(value)sessionStorage.setItem(sessionKey,JSON.stringify(value));else sessionStorage.removeItem(sessionKey)}
  let teacherDisplayName='';
  function initials(name){return name.trim().split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'KM'}
  function syncExplorer(name=''){teacherDisplayName=name;const title=$('#profileTitle'),avatar=$('.profile-avatar'),button=$('#profileButton');if(name){title.textContent=name;avatar.textContent=initials(name);button.textContent=initials(name)}else{title.textContent='Kimi';avatar.textContent='KM';button.textContent='KM'}}
  async function api(options={}){const response=await fetch('/api/teacher-auth',{...options,headers:{'Content-Type':'application/json',...(options.token?{Authorization:`Bearer ${options.token}`}:{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'request_failed');return body}
  const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  async function loadInvitations(token){const status=$('#teacherAdminStatus'),list=$('#teacherInvitationList');status.textContent=english?'Loading…':'Chargement…';try{const result=await api({method:'POST',token,body:JSON.stringify({action:'list-invitations'})});list.innerHTML=result.invitations.map(item=>`<article class="teacher-invitation-row"><div><strong>${escapeHtml(item.email)}</strong><span>${copy.roles[item.role]||item.role}</span></div><button type="button" data-invitation-email="${escapeHtml(item.email)}" data-invitation-role="${escapeHtml(item.role)}" data-invitation-active="${!item.active}" class="${item.active?'suspend':''}">${item.active?(english?'Suspend':'Suspendre'):(english?'Reactivate':'Réactiver')}</button></article>`).join('')||`<p>${english?'No invitations yet.':'Aucune invitation.'}</p>`;status.textContent=''}catch{status.textContent=copy.error}}
  function open(){const modal=$('#teacherAccountModal');modal.hidden=false;document.body.classList.add('modal-open');loadSession()}
  function close(){const modal=$('#teacherAccountModal');modal.hidden=true;document.body.classList.remove('modal-open')}
  function showProfile(data,token){$('#teacherLoginForm').hidden=true;$('#teacherLoginSent').hidden=true;$('#teacherAccountUnavailable').hidden=true;$('#teacherProfileForm').hidden=false;$('#teacherSessionEmail').textContent=data.user.email;$('#teacherRole').textContent=copy.roles[data.profile.role]||copy.roles.teacher;$('#teacherDisplayName').value=data.profile.display_name||'';$('#teacherSchool').value=data.profile.school_name||'';$('#teacherProvince').value=data.profile.education_province||'Kinshasa';$('#teacherCycle').value=data.profile.cycle||'primary';$('#teacherSubjects').value=data.profile.subjects||'';$('#teacherAccountButton').classList.add('authenticated');$('#teacherAccountButton').textContent=english?'Teacher ✓':'Enseignant ✓';syncExplorer(data.profile.display_name||'');adminPanel.hidden=data.profile.role!=='admin';setSession({token,email:data.user.email});if(data.profile.role==='admin')loadInvitations(token)}
  async function loadSession(){const session=getSession();if(!session?.token)return;try{showProfile(await api({token:session.token}),session.token)}catch{setSession(null);$('#teacherProfileForm').hidden=true;$('#teacherLoginForm').hidden=false;$('#teacherAccountButton').classList.remove('authenticated');$('#teacherAccountButton').textContent=copy.button}}
  const hash=new URLSearchParams(location.hash.startsWith('#')?location.hash.slice(1):'');if(hash.has('access_token')){setSession({token:hash.get('access_token')});history.replaceState(null,'',`${location.pathname}${location.search}#teacherAccount`);open()}
  $('#teacherAccountButton').addEventListener('click',open);document.querySelectorAll('[data-close-teacher-account]').forEach(element=>element.addEventListener('click',close));
  $('#teacherLoginForm').addEventListener('submit',async event=>{event.preventDefault();const button=$('#teacherLoginButton');button.disabled=true;try{await api({method:'POST',body:JSON.stringify({action:'magic-link',email:$('#teacherEmail').value.trim(),redirectTo:`${location.origin}${location.pathname}`})});$('#teacherLoginForm').hidden=true;$('#teacherLoginSent').hidden=false;$('#teacherLoginSent').textContent=copy.sent}catch(error){if(error.message==='not_configured'){$('#teacherAccountUnavailable').hidden=false;$('#teacherAccountUnavailable').textContent=copy.unavailable}else{$('#teacherLoginHelp').textContent=copy.error}}finally{button.disabled=false}});
  $('#teacherProfileForm').addEventListener('submit',async event=>{event.preventDefault();const session=getSession();if(!session?.token)return;const status=$('#teacherProfileStatus');try{const result=await api({method:'POST',token:session.token,body:JSON.stringify({action:'profile',display_name:$('#teacherDisplayName').value.trim(),school_name:$('#teacherSchool').value.trim(),education_province:$('#teacherProvince').value,cycle:$('#teacherCycle').value,subjects:$('#teacherSubjects').value.trim()})});showProfile(result,session.token);status.textContent=copy.saved}catch{status.textContent=copy.error}});
  $('#teacherInvitationForm').addEventListener('submit',async event=>{event.preventDefault();const session=getSession(),status=$('#teacherAdminStatus');if(!session?.token)return;try{await api({method:'POST',token:session.token,body:JSON.stringify({action:'save-invitation',email:$('#invitationEmail').value.trim(),role:$('#invitationRole').value,active:true})});event.target.reset();status.textContent=english?'Invitation added.':'Invitation ajoutée.';await loadInvitations(session.token)}catch{status.textContent=copy.error}});
  $('#teacherInvitationList').addEventListener('click',async event=>{const button=event.target.closest('[data-invitation-email]'),session=getSession();if(!button||!session?.token)return;button.disabled=true;try{await api({method:'POST',token:session.token,body:JSON.stringify({action:'save-invitation',email:button.dataset.invitationEmail,role:button.dataset.invitationRole,active:button.dataset.invitationActive==='true'})});await loadInvitations(session.token)}catch{$('#teacherAdminStatus').textContent=copy.error}finally{button.disabled=false}});
  $('#refreshInvitations').addEventListener('click',()=>{const session=getSession();if(session?.token)loadInvitations(session.token)});
  $('#teacherLogout').addEventListener('click',()=>{setSession(null);syncExplorer();adminPanel.hidden=true;$('#teacherProfileForm').hidden=true;$('#teacherLoginForm').hidden=false;$('#teacherAccountButton').classList.remove('authenticated');$('#teacherAccountButton').textContent=copy.button});
  new MutationObserver(()=>{if(teacherDisplayName&&$('#profileTitle').textContent!==teacherDisplayName)syncExplorer(teacherDisplayName)}).observe($('#profileTitle'),{childList:true});loadSession();
})();
