const fs=require('fs');
const vm=require('vm');
function assert(condition,message){if(!condition)throw new Error(message)}
const required=['index.html','privacy.html','app.js','i18n.js','content-en.js','math.js','music-game.js','chess-game.js','pilot-measure.js','pilot-measure.css','province-boundaries.js','territory-boundaries.js','territory-catalog.js','generate-territory-map.js','drc-adm2.geojson','sw.js','manifest.webmanifest','vercel.json','hardening.css','responsive.css','real-map.css','territories.css','achievements.css','kingdoms.css','communities.css','food.css','environment.css','resources.css','creativity.css','math.css','music-game.css','chess-game.css','icon.svg','README.md','PRESENTATION.md','CHANGELOG.md'];
required.forEach(file=>assert(fs.existsSync(file),`Missing required file: ${file}`));
['pilot-dashboard.js','pilot-dashboard.css','teacher-account.js','teacher-account.css','teacher-account-responsive.css','api/teacher-auth.js','supabase/teacher-accounts.sql','supabase/teacher-invitation-allowlist.sql','supabase/teacher-display-name.sql','supabase/teacher-admin.sql','TEACHER_ACCOUNTS.md'].forEach(file=>assert(fs.existsSync(file),`Missing required file: ${file}`));
['history-timeline.js','history-timeline.css','content-review.js','content-review.css','sources.js','sources.css'].forEach(file=>assert(fs.existsSync(file),`Missing required file: ${file}`));
['curriculum.js','curriculum.css','class-mode.js','class-mode.css','digital-code.js','digital-code.css'].forEach(file=>assert(fs.existsSync(file),`Missing required file: ${file}`));
assert(fs.existsSync('mission.css'),'Missing required file: mission.css');
const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest','utf8'));
const vercel=JSON.parse(fs.readFileSync('vercel.json','utf8'));
assert(manifest.start_url==='./index.html','Manifest start URL is incorrect');
const globalHeaders=vercel.headers.find(entry=>entry.source==='/(.*)').headers;
const headerNames=new Set(globalHeaders.map(header=>header.key));
['Content-Security-Policy','X-Content-Type-Options','Referrer-Policy','Permissions-Policy','X-Frame-Options','Cross-Origin-Opener-Policy'].forEach(name=>assert(headerNames.has(name),`Missing security header: ${name}`));
const html=fs.readFileSync('index.html','utf8');
assert(!/https?:\/\//.test(html),'index.html contains an external network dependency');
assert(html.includes('privacy.html'),'Privacy link is missing');
const privacy=fs.readFileSync('privacy.html','utf8');
assert(privacy.includes('id="privacy-en"')&&privacy.includes('What Mboka stores')&&privacy.includes('Children and school environments'),'Complete English privacy information is missing');
const readme=fs.readFileSync('README.md','utf8'),presentation=fs.readFileSync('PRESENTATION.md','utf8');
for(const phrase of ['two-team mode','lesson plans','progress reports'])assert(readme.includes(phrase),`README is missing current feature: ${phrase}`);
for(const phrase of ['deux équipes','plan de leçon','rapport individuel de progression','two-team classroom mode','lesson plan','individual progress report'])assert(presentation.includes(phrase),`Presentation is missing current feature: ${phrase}`);
assert(html.includes('id="privacyLink"'),'Privacy link must have a stable translation target');
assert(html.includes('id="mission"')&&html.includes('id="missionTitle"')&&html.includes('NOS ENGAGEMENTS'),'Vision, mission, or commitments are missing');
assert(fs.readFileSync('i18n.js','utf8').includes("'#missionTitle'"),'Mission heading must preserve its intentional line break during translation');
assert(!html.includes('1 200+ explorateurs'),'Unverified audience claims must not appear in the interface');
assert(!/(stripe|paypal|checkout|advertis(?:e|ing)|tracking pixel)/i.test(html),'Core application must not include payment, advertising, or tracking integrations');
assert(!/<input[^>]+type=["'](?:email|password)["']/i.test((html.match(/<section class="pilot-section"[\s\S]*?<\/section>/)||[''])[0]),'Learner-facing pilot must not request account credentials');
assert(readme.includes('Engagement d’accès éducatif')&&readme.includes('sans paiement'),'README must document the core educational access commitment');
assert(privacy.includes('Accès éducatif de base')&&privacy.includes('sans paiement'),'Privacy policy must document the core educational access commitment');
assert(!fs.readFileSync('i18n.js','utf8').includes("'footer>p:nth-of-type(2)'"),'Localization must not overwrite the privacy-link container');
assert(html.includes('id="pilotForm"'),'Anonymous pilot form is missing');
assert(html.includes('id="pilotMeasure"')&&html.includes('id="exportPilotResults"'),'Measurable pre/post pilot flow is missing');
assert(html.includes('id="contentReviewForm"')&&html.includes('id="exportContentReviews"'),'Anonymous educational content-review workflow is missing');
const pilotMeasure=fs.readFileSync('pilot-measure.js','utf8');
const contentReview=fs.readFileSync('content-review.js','utf8');assert(contentReview.includes('mbokaContentReviews')&&contentReview.includes('cultural_context')&&contentReview.includes('suggested_source'),'Content-review evidence export is incomplete');
assert(html.includes('id="pilotExistingCode"')&&pilotMeasure.includes("phase==='pre'")&&pilotMeasure.includes("phase==='post'"),'Reusable anonymous pre/post learner codes are missing');
assert(pilotMeasure.includes("'pre_score','post_score','gain'")&&pilotMeasure.includes('mbokaPilotTests'),'Pilot learning-gain export is missing');
const pilotDashboard=fs.readFileSync('pilot-dashboard.js','utf8');
assert(html.includes('id="impactDashboard"')&&html.includes('id="impactCsvFile"')&&html.includes('id="printImpactReport"'),'Local pilot impact dashboard is missing');
assert(pilotDashboard.includes('parseCsv')&&pilotDashboard.includes('2*1024*1024')&&pilotDashboard.includes('window.print()'),'Pilot dashboard validation, local analysis, or printable report is missing');
const teacherAccount=fs.readFileSync('teacher-account.js','utf8'),teacherApi=fs.readFileSync('api/teacher-auth.js','utf8'),teacherSql=fs.readFileSync('supabase/teacher-accounts.sql','utf8');
assert(html.includes('id="teacherAccountModal"')&&html.includes('id="teacherLoginForm"'),'Teacher account interface is missing');
assert(teacherAccount.includes('sessionStorage')&&teacherAccount.includes('access_token'),'Teacher session handling is incomplete');
assert(teacherAccount.includes('teacherDisplayName')&&teacherAccount.includes('syncExplorer'),'Teacher display name synchronization is incomplete');
assert(teacherAccount.includes('teacherAdminPanel')&&teacherAccount.includes('list-invitations')&&teacherApi.includes('admin_upsert_teacher_invitation'),'Teacher invitation administration is incomplete');
assert(teacherApi.includes('create_user:true')&&teacherApi.includes('SUPABASE_ANON_KEY'),'Invitation-only passwordless authentication is incomplete');
assert(teacherSql.includes('teacher_invitations')&&teacherSql.includes('display_name')&&teacherSql.includes('enable row level security')&&teacherSql.includes('protect_teacher_role')&&teacherSql.includes('hook_restrict_teacher_signup'),'Teacher allowlist, display name, auth hook, profile RLS, or role protection is missing');
assert(html.includes('id="mathUnitGrid"')&&html.includes('id="mathLevelPicker"'),'Everyday mathematics interface is missing');
assert(html.includes('lab-pedagogy-card')&&html.includes('FICHE PÉDAGOGIQUE')&&html.includes('preuve'),'Music and chess pedagogical cards are missing');
assert(html.includes('math-pedagogy-card')&&html.includes('usage adaptable en classe'),'Math pedagogical card is missing');
assert((html.match(/class="activity-pedagogy-card/g)||[]).length>=6,'Interactive activity pedagogical cards are missing');
assert(html.includes('daily-pedagogy-card')&&html.includes('sélectionner une information')&&html.includes('reformulation fidèle'),'Daily discovery pedagogical fields are incomplete');
assert(fs.readFileSync('app.js','utf8').includes('activityAudience')&&fs.readFileSync('app.js','utf8').includes('Public :'),'Activity audience guidance is missing');
assert(fs.readFileSync('app.js','utf8').includes('activity-audience')&&fs.readFileSync('app.js','utf8').includes('validator'),'Activity recommended-reviewer guidance is missing');
assert(fs.readFileSync('app.js','utf8').includes('mbokaActivityDecision')&&fs.readFileSync('curriculum.js','utf8').includes('mbokaMatrixDecision'),'Activity decision workflow is missing');
assert(html.includes('daily-pedagogy-card')&&html.includes('journey-pedagogy-card')&&html.includes('province-pedagogy-card'),'Discovery and map pedagogical cards are missing');
assert(html.includes('id="quizMode"')&&html.includes('id="quizTopic"')&&html.includes('id="quizProvince"'),'Quiz mode, topic, or province controls are missing');
assert(html.includes('id="musicKeyboard"')&&html.includes('id="musicSectionList"'),'Interactive music-learning interface is missing');
assert(html.includes('id="memoryCollection"')&&html.includes('id="memoryDifficulty"'),'Memory collections or difficulty controls are missing');
assert(html.includes('id="chessBoard"')&&html.includes('id="chessSectionList"'),'Interactive chess-learning interface is missing');
assert(html.includes('id="chessSpeak"'),'Chess spoken-instruction control is missing');
assert(html.includes('class="skip-link"')&&html.includes('class="module-nav"'),'Accessible quick navigation is missing');
assert(html.includes('class="pathway-menu"')&&html.includes('href="#enseignants">Enseignants</a>'),'Teacher and learning-path navigation is missing');
assert(html.includes('id="histoire"')&&html.includes('id="historyTimeline"')&&html.includes('href="#histoire">Histoire</a>'),'Interactive history timeline or navigation is missing');
assert(html.includes('id="sources"')&&html.includes('id="sourceGrid"')&&html.includes('href="#sources">Sources</a>'),'Source library or navigation is missing');
assert(html.includes('href="#musicLab">Musique</a>')&&html.includes('href="#chessLab">Échecs</a>'),'Music and chess navigation links are missing');
assert(html.includes('id="provinceBoundaryLayer"')&&html.includes('geoBoundaries COD ADM1'),'Real 26-province map or attribution is missing');
assert(html.includes('id="territoryBoundaryLayer"')&&html.includes('geoBoundaries COD ADM2'),'145-territory map or attribution is missing');
const territoryMap=fs.readFileSync('territory-boundaries.js','utf8');
assert((territoryMap.match(/"name":/g)||[]).length===145,'Territory map must contain exactly 145 territories');
assert(html.includes('id="worksheetLevel"')&&html.includes('id="worksheetTopic"'),'Teacher worksheet filters are missing');
assert(html.includes('Générer une fiche d’exercices')&&!html.includes('Préparer une activité'),'Teacher worksheet and class-session labels must be distinct');
assert(html.includes('id="classModeForm"')&&html.includes('id="classSessionCode"')&&html.includes('id="exportClassSessions"'),'Local teacher class mode is missing');
const classMode=fs.readFileSync('class-mode.js','utf8');assert(classMode.includes('mbokaClassSessions')&&classMode.includes('crypto.getRandomValues')&&classMode.includes('session_code'),'Class session privacy, code generation, or CSV export is incomplete');
assert(html.includes('id="classSessionHistory"')&&classMode.includes('renderHistory')&&classMode.includes('data-reopen-session')&&classMode.includes('data-remove-session'),'Class session history, reopening, or removal is incomplete');
assert(classMode.includes('escapeHtml(session.title)')&&classMode.includes('confirm(copy[language()].confirm)'),'Class session history must escape stored content and confirm deletion');
const classModeCss=fs.readFileSync('class-mode.css','utf8');assert(classModeCss.includes('body.class-session-printing>main{display:block!important}'),'Class-session print mode must override the worksheet print rule');
assert(html.includes('id="numerique"')&&html.includes('id="digitalTopicGrid"')&&html.includes('id="digitalAnswers"'),'Digital Mboka interface is missing');
const digitalCode=fs.readFileSync('digital-code.js','utf8');assert((digitalCode.match(/id:'/g)||[]).length===6,'Digital Mboka must contain exactly six non-duplicated MVP topics');
for(const reference of ['Article 1','Articles 183–270','Articles 271–340','Articles 83–160','Articles 48–72','Articles 348–363'])assert(digitalCode.includes(reference),`Digital Code reference is missing: ${reference}`);
assert((digitalCode.match(/\{q:/g)||[]).length===6&&(digitalCode.match(/,correct:\d/g)||[]).length===6&&digitalCode.includes('mbokaDigitalBest'),'Digital citizenship quiz must contain six scored situations');
assert(digitalCode.includes('not legal advice')&&digitalCode.includes('ne constituent pas un avis juridique'),'Digital Mboka legal disclaimer must be bilingual');
assert(digitalCode.includes('anapi.cd/services-financiers-pilier-global')&&digitalCode.includes('droitnumerique.cd/code-du-numerique-congolais-rdc-pdf'),'Digital Code references are missing');
assert(fs.readFileSync('i18n.js','utf8').includes("'.trust p'"),'Trust-card emphasis must render as HTML, not literal markup');
assert(html.includes('id="printLessonPlan"'),'Printable lesson-plan button is missing');
assert(html.includes('curriculum.js')&&fs.readFileSync('curriculum.js','utf8').includes('referentielPedagogique'),'RDC curriculum reference tool is missing');
const hardening=fs.readFileSync('hardening.css','utf8');
assert(hardening.includes('--green2:#0e7554')&&hardening.includes('--orange:#b54b28'),'Accessible secondary palette overrides are missing');
const responsive=fs.readFileSync('responsive.css','utf8');
assert(responsive.includes('grid-template-areas:"heading game" "pedagogy game"')&&responsive.includes('grid-template-areas:"intro card" "pedagogy card"'),'Sprint and quiz pedagogical layouts must not create empty grid columns');
const curriculum=fs.readFileSync('curriculum.js','utf8');
for(const source of ['edu-nc.gouv.cd/niveaux','edu-nc.gouv.cd/programmes-nationaux','PE7-MATH.pdf','PE8-MATH','PE7-SVT.pdf','PE7-SPTTIC.pdf','3e-Sec_1-HS_MATH','6e-Sec_4-HS_SVT','EDUCATION-CIVIQUE-ET-MORALE-PRIMAIRE.pdf','Alphabetisation-fonctionnelle.pdf','ELECTRICITE.pdf','ELECTRONIQUE.pdf','Curriculum-Commerciale-et-Gestion.pdf'])assert(curriculum.includes(source),`Curriculum source is missing: ${source}`);
for(const phrase of ['savoirs essentiels','compétences','indicateurs pédagogiques','adaptation par'])assert(curriculum.includes(phrase),`Curriculum quality note is missing: ${phrase}`);
for(const code of ['MM1.39','MM1.41','MM1.42–MM1.44','MM1.45','MM1.46–MM1.47','MM1.48','MM1.62','MM1.63–MM1.64','MM1.65','MM1.66','MM1.67'])assert(curriculum.includes(code),`Curriculum matrix entry is missing: ${code}`);
for(const code of ['MM2.1','MM2.2','MM2.3','MM2.4','MM2.5','MM2.6','MM2.7','MM2.8','MM2.9','MM2.10','MM2.11','MM2.12'])assert(curriculum.includes(code),`Secondary curriculum matrix entry is missing: ${code}`);
for(const code of ['MSVT1.1','MSVT1.2','MSVT1.3','MSVT1.4','MSVT1.5–MSVT1.6','MSVT1.7','MSVT1.8','MSVT1.9','MSVT1.10'])assert(curriculum.includes(code),`SVT curriculum matrix entry is missing: ${code}`);
for(const phrase of ['SPTTIC 7e · matière','SPTTIC 7e · substances','SPTTIC 7e · mélanges','SPTTIC 7e · eau','SPTTIC 7e · air'])assert(curriculum.includes(phrase),`SPTTIC curriculum domain is missing: ${phrase}`);
for(const code of ['MSP1.1','MSP1.2'])assert(curriculum.includes(code),`SPTTIC physical quantity entry is missing: ${code}`);
for(const phrase of ['SPTTIC 7e · technologie','SPTTIC 7e · architecture','SPTTIC 7e · alimentation','SPTTIC 7e · métiers','SPTTIC 7e · TIC'])assert(curriculum.includes(phrase),`SPTTIC technology domain is missing: ${phrase}`);
for(const code of ['MTIC1.1','MTIC1.2','MTIC1.3','MTIC1.4','MTIC1.5','MTIC1.6','MTIC1.7','MTIC1.8','MTIC1.9','MTIC1.10','MTIC1.11','MTIC1.12'])assert(curriculum.includes(code),`TIC curriculum entry is missing: ${code}`);
for(const code of ['MTIC2.1','MTIC2.2','MTIC2.3','MTIC2.4','MTIC2.5','MTIC2.6','MTIC2.7','MTIC2.8','MTIC2.9','MTIC2.10'])assert(curriculum.includes(code),`TIC 8e curriculum entry is missing: ${code}`);
assert(curriculum.includes('Adaptation Mboka')&&curriculum.includes('Preuve'),'Curriculum matrix must separate adaptation and evidence');
assert(curriculum.includes("document.body.classList.add('curriculum-printing')")&&fs.readFileSync('curriculum.css','utf8').includes('.curriculum-printing #referentielPedagogique'),'Curriculum print mode must isolate the selected preparation');
assert(curriculum.includes('data-matrix-print')&&curriculum.includes('matrix-print-target'),'Individual curriculum-unit printing is missing');
assert(curriculum.includes('matrix-archive-meta')&&curriculum.includes('adaptation pédagogique Mboka'),'Curriculum archive metadata is missing');
assert(curriculum.includes('Cycle :</strong> 7e · <strong>Domaine :</strong> DAS'),'Math grade seven archive metadata is missing');
assert(curriculum.includes('matrix-coverage-fields')&&curriculum.includes('recommended_reviewer')&&curriculum.includes('Indicateur proposé'),'Curriculum coverage fields are missing');
assert(curriculum.includes('Public conseillé')&&curriculum.includes('12–14 ans'),'Curriculum audience guidance is missing');
assert(curriculum.includes('Cadre de responsabilité')&&curriculum.includes('Ministère')&&curriculum.includes('Validation'),'Curriculum authority distinction is missing');
assert(curriculum.includes('matrixCycleFilter')&&curriculum.includes('matrixDomainFilter')&&curriculum.includes('applyMatrixFilters'),'Curriculum matrix filters are missing');
assert(curriculum.includes('exportMatrixDecisions')&&curriculum.includes('mboka-curriculum-decisions-'),'Curriculum decision CSV export is missing');
assert(curriculum.includes('matrixDecisionSummary')&&curriculum.includes('updateDecisionSummary'),'Curriculum decision summary is missing');
assert(curriculum.includes('groups')&&curriculum.includes('Par cycle/domaine'),'Curriculum cycle-domain summary is missing');
assert(curriculum.includes('Aucune unité détaillée intégrée pour ce filtre'),'Curriculum empty-filter status is missing');
assert(curriculum.includes('mbokaMatrixCycle')&&curriculum.includes('mbokaMatrixDomain'),'Curriculum filter persistence is missing');
assert(html.includes('id="printProgress"'),'Printable progress-report button is missing');
assert(html.includes('id="sprintMode"'),'Province Sprint team-mode control is missing');
const anonymousPilotHtml=(html.match(/<section class="pilot-section"[\s\S]*?<\/section>/)||[''])[0];
assert(!/<input[^>]+type=["'](?:email|password)["']/i.test(anonymousPilotHtml),'Anonymous learner pilot must not request email or passwords');
const app=fs.readFileSync('app.js','utf8');
const history=fs.readFileSync('history-timeline.js','utf8');
const sources=fs.readFileSync('sources.js','utf8');assert((sources.match(/url:'https:\/\//g)||[]).length>=7&&sources.includes('edu-nc.gouv.cd/programmes-nationaux')&&sources.includes('Mboka pedagogical adaptation'),'Documentary source library is incomplete');
assert((history.match(/period:'/g)||[]).length===8&&['early','colonial','independence','contemporary'].every(period=>history.includes(`${period}:`)),'History timeline must contain eight events and four filters');
const math=fs.readFileSync('math.js','utf8');
assert(math.includes('const mathUnits=')&&((math.match(/title:\[/g)||[]).length===10),'Everyday mathematics must contain 10 units');
const music=fs.readFileSync('music-game.js','utf8');
assert(music.includes('const musicSections=')&&((music.match(/title:\[/g)||[]).length===4),'Music learning must contain 4 sections');
assert(music.includes('musicIsiOS')&&music.includes('playMusicFile'),'Music learning must include the iOS audio-file fallback');
assert(music.includes('highlightMusicKey(note)'),'Music playback must visually highlight each note');
for(const note of ['C','Cs','D','Ds','E','F','Fs','G','Gs','A','As','B'])assert(fs.existsSync(`music-${note}.wav`),`Missing iOS music note: ${note}`);
const chess=fs.readFileSync('chess-game.js','utf8');
assert(chess.includes('const chessSections=')&&((chess.match(/title:\[/g)||[]).length===7),'Chess learning must contain 7 sections');
assert(chess.includes('mbokaChessProgress')&&chess.includes('saveChessSection'),'Chess learning must save measurable local progress');
assert(chess.includes('class="chess-piece"'),'Chess pieces must have dedicated responsive sizing');
assert(fs.readFileSync('responsive.css','utf8').includes('.chess-square.dark .chess-coord'),'Chess coordinates must remain legible on dark squares');
assert(chess.includes("querySelector('#chessSpeak')")&&chess.includes('speakPhrase'),'Chess instructions must support spoken playback');
assert(chess.includes("control.textContent='🔊'"),'Spoken-text controls must use the speaker symbol');
assert(app.includes("soundEnabled?'🔊':'🔇'"),'Global sound control must use speaker symbols');
assert(app.includes('mbokaSpeechRate')&&app.includes('speechRates.includes'),'Speech playback speed must be stored and validated locally');
assert(html.includes('id="speechRate"')&&html.includes('id="lessonSpeak"'),'Playback speed and lesson listening controls are missing');
assert(app.includes('renderLessonPlan'),'Printable lesson-plan generator is missing');
assert(app.includes('renderProgressReport'),'Printable progress-report generator is missing');
assert(app.includes("sprintMode==='team'"),'Province Sprint team-mode logic is missing');
assert(app.includes('buildProvinceQuiz')&&app.includes('quizTopicGroups')&&app.includes('quizStorageKey'),'Expanded province, topic, and difficulty quiz modes are missing');
assert(app.includes('memoryCollections')&&app.includes('memoryPairTarget')&&app.includes('memoryRecordKey'),'Expanded memory collections and levels are missing');
assert((app.match(/\{id:'(?:okapi|rumba|pondu|congo|virunga|kinshasa|fufu|lingala)'/g)||[]).length===8,'The default memory collection must contain eight pairs for advanced mode');
assert(!/\beval\s*\(|new\s+Function\s*\(/.test(app),'Unsafe dynamic code execution found');
assert((app.match(/name:'/g)||[]).length>=4&&app.includes('achievementProfiles'),'Achievement profiles are incomplete');
assert(app.includes('kingdomProfiles')&&['Kongo','Luba','Lunda','Kuba'].every(name=>app.includes(`name:'${name}'`)),'Traditional kingdom profiles are incomplete');
assert(app.includes('communityProfiles')&&app.includes('renderCommunities'),'Community cultural profiles are incomplete');
assert(app.includes('foodProfiles')&&['Pondu','Fufu','Liboke','Chikwangue','Mikate'].every(name=>app.includes(`name:'${name}'`)),'Food culture profiles are incomplete');
assert(app.includes('environmentProfiles')&&app.includes('renderEnvironment'),'Environment and science profiles are incomplete');
assert(app.includes('resourceProfiles')&&app.includes('supplySteps')&&app.includes('renderResources'),'Natural-resource learning profiles are incomplete');
assert(app.includes('creativityProfiles')&&app.includes('renderCreativity'),'Music, art and creativity profiles are incomplete');
for(const [name,count] of [['provinces',26],['provinceDetails',26],['mapPositions',26]]){const match=app.match(new RegExp(`const ${name} =? ?\\[(.*?)\\];`,'s'));assert(match,`Could not find ${name}`);const actual=name==='mapPositions'?(match[1].match(/\[\d+,\d+\]/g)||[]).length:(match[1].match(/\['/g)||[]).length;assert(actual===count,`${name} has ${actual} entries; expected ${count}`)}
for(const name of ['explorerQuestions','masterQuestions']){const match=app.match(new RegExp(`const ${name}=\\[(.*?)\\];`,'s'));assert(match&&((match[1].match(/\{topic:/g)||[]).length===10),`${name} must contain 10 questions`)}
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('content-en.js','utf8'),sandbox);const en=sandbox.window.enContent;
const mapSandbox={window:{}};vm.runInNewContext(fs.readFileSync('province-boundaries.js','utf8'),mapSandbox);assert(mapSandbox.window.drcProvinceBoundaries.length===26,'Real province boundary map must contain 26 provinces');
const territorySandbox={window:{}};vm.runInNewContext(fs.readFileSync('territory-boundaries.js','utf8'),territorySandbox);assert(territorySandbox.window.drcTerritoryBoundaries.length===145,'Real territory boundary map must contain 145 territories');assert(new Set(territorySandbox.window.drcTerritoryBoundaries.map(item=>item.province)).size===25,'Territories must be grouped across 25 provinces');
assert(en.provinces.length===26,'English province profiles must contain 26 entries');assert(en.questions.length===10&&en.levelQuestions.explorer.length===10&&en.levelQuestions.master.length===10,'English quiz banks must contain 10 questions each');
assert(en.provinceProfiles.length===26&&en.provinceProfiles.every(profile=>profile.length===5),'English cultural province profiles must contain 26 complete entries');
assert(app.includes("title:english?'Essential facts':'Repères essentiels'")&&app.includes("title:english?'Territories':'Territoires'")&&app.includes('territorySummary'),'Structured province encyclopedia is missing');
assert(app.includes("title:english?'Editorial status':'Statut éditorial'"),'Province editorial-review status is missing');
const profileMatch=app.match(/const provinceProfiles = \[(.*?)\];/s);assert(profileMatch&&((profileMatch[1].match(/^  \[/gm)||[]).length===26),'French cultural province profiles must contain 26 entries');
const build=fs.readFileSync('build.js','utf8'),worker=fs.readFileSync('sw.js','utf8');
const buildFiles=[...build.matchAll(/'([^']+)'/g)].map(match=>match[1]).filter(file=>fs.existsSync(file)&&fs.statSync(file).isFile());
for(const file of buildFiles)assert(worker.includes(`./${file}`)||file==='sw.js',`Service worker does not cache build asset: ${file}`);
console.log('Mboka validation passed: security, privacy, content counts, and offline assets.');
